services:
  - type: web
    name: valichord-demo
    runtime: docker
    dockerfilePath: ./demo/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: VALICHORD_RESEARCHER_URL
        value: http://152.67.153.149:3001
      - key: VALICHORD_VALIDATOR_1_URL
        value: http://152.67.153.149:3002
      - key: VALICHORD_VALIDATOR_2_URL
        value: http://152.67.153.149:3003
      - key: VALICHORD_VALIDATOR_3_URL
        value: http://152.67.153.149:3004
