"""
ValiChord Auto-Generate
Draft File Generator
Produces all _DRAFT output files per ValiChord Specification v15
"""

from pathlib import Path
import re
from datetime import datetime
import re


CODE_EXTENSIONS = {
    '.py', '.r', '.rmd', '.qmd', '.jl', '.m', '.sh', '.bash',
    '.do', '.sas', '.ado', '.c', '.cpp', '.f', '.f90',
    '.sql', '.rs', '.go', '.java', '.js', '.ts'
}

NOTEBOOK_EXTENSIONS = {'.ipynb', '.mlx', '.rmd', '.qmd'}

README_NAMES = {'readme.md', 'readme.txt', 'readme.rst', 'readme'}

DEPENDENCY_FILES = {
    'requirements.txt', 'environment.yml', 'environment.yaml',
    'pipfile.lock', 'poetry.lock', 'setup.py', 'pyproject.toml',
    'renv.lock', 'cargo.toml', 'package.json'
}


def generate_all_drafts(repo_dir, all_files, findings, output_dir):
    """Generate all _DRAFT files."""

    modes_found = {f['mode'] for f in findings}

    _generate_inventory(repo_dir, all_files, output_dir)
    _generate_readme_draft(repo_dir, all_files, findings, output_dir)
    _generate_requirements_draft(repo_dir, all_files,
                                  findings, output_dir)
    _generate_quickstart_draft(repo_dir, all_files,
                                findings, output_dir)
    _generate_licence_draft(output_dir)
    generate_proposed_corrections(repo_dir, all_files, findings, output_dir)


# ── INVENTORY_DRAFT.md ───────────────────────────────────────────────────────

def _generate_inventory(repo_dir, all_files, output_dir):
    """Generate INVENTORY_DRAFT.md — full file listing."""

    now = datetime.now().strftime('%Y-%m-%d %H:%M')
    lines = [
        '# ValiChord Repository Readiness Check — File Inventory',
        '',
        f'**Generated:** {now}',
        f'**Total files:** {len(all_files)}',
        '',
        '> This inventory was generated by automated analysis.',
        '> File purpose descriptions are structural only — '
        'derived from',
        '> code evidence where available. Semantic descriptions',
        '> are not inferred from filenames.',
        '',
        '---',
        '',
        '## File Listing',
        '',
        '| File | Type | Size | Notes |',
        '|---|---|---|---|',
    ]

    for f in sorted(all_files, key=lambda x: str(x)):
        rel = f.relative_to(repo_dir)
        size = f.stat().st_size
        size_str = (f'{size:,} bytes' if size < 10240
                    else f'{size/1024:.1f} KB')
        ftype = _classify_file(f)
        notes = _file_notes(f)
        lines.append(f'| `{rel}` | {ftype} | {size_str} | {notes} |')

    lines += [
        '',
        '---',
        '',
        f'*Generated by ValiChord Repository Readiness Check — v15 — {now}*',
    ]

    out = output_dir / 'INVENTORY_DRAFT.md'
    out.write_text('\n'.join(lines), encoding='utf-8-sig')
    print(f"  → INVENTORY_DRAFT.md ({len(all_files)} files)")


def _classify_file(f):
    ext = f.suffix.lower()
    if ext in CODE_EXTENSIONS:
        return 'Code'
    if ext in NOTEBOOK_EXTENSIONS:
        return 'Notebook'
    if ext in {'.md', '.txt', '.rst', '.html', '.tex'}:
        return 'Documentation'
    if ext in {'.csv', '.tsv', '.xlsx', '.json', '.parquet',
               '.rds', '.rdata', '.dta', '.sav', '.mat',
               '.pkl', '.npy', '.npz', '.hdf5', '.h5'}:
        return 'Data'
    if ext in {'.png', '.jpg', '.jpeg', '.pdf', '.svg', '.tif'}:
        return 'Figure/Image'
    if f.name.lower() in DEPENDENCY_FILES:
        return 'Dependency spec'
    if ext in {'.yml', '.yaml', '.toml', '.ini', '.cfg'}:
        return 'Configuration'
    if ext in {'.sh', '.bash'}:
        return 'Shell script'
    if ext in {'.gpg', '.enc', '.secret', '.age', '.asc'}:
        return '⚠️ POSSIBLY ENCRYPTED'
    return 'Other'


def _file_notes(f):
    name = f.name.lower()
    ext = f.suffix.lower()
    if ext in {'.gpg', '.enc', '.secret', '.age', '.asc'}:
        return '🔴 POSSIBLY ENCRYPTED — may be unusable without key'
    if name in README_NAMES:
        return 'README'
    if name in {'licence', 'license', 'licence.md',
                'license.md', 'licence.txt', 'license.txt'}:
        return 'Licence file'
    if name == 'requirements.txt':
        return 'Dependency specification'
    if name == 'dockerfile':
        return 'Container definition'
    if re.match(r'^0*[0-9]+[_\-]', f.name):
        return 'Numbered script — execution order implied'
    return ''


# ── README_DRAFT.md ──────────────────────────────────────────────────────────

def _generate_readme_draft(repo_dir, all_files, findings, output_dir):
    """Generate README_DRAFT.md."""

    now = datetime.now().strftime('%Y-%m-%d %H:%M')

    # try to find existing readme content
    existing_readme = ''
    for f in all_files:
        if f.name.lower() in README_NAMES:
            try:
                existing_readme = f.read_text(
                    encoding='utf-8', errors='ignore'
                )
            except Exception:
                pass
            break

    lines = [
        '# [TITLE OF PAPER — YOU MUST COMPLETE THIS]',
        '',
        '> ⚠️ **README_DRAFT.md** — This file was generated by '
        'ValiChord Repository Readiness Check.',
        '> All sections marked [YOU MUST COMPLETE THIS] require '
        'your input.',
        '> Verify all content, then rename to `README.md`.',
        '',
        '---',
        '',
        '## Study Identification',
        '',
        '- **Paper title:** [YOU MUST COMPLETE THIS]',
        '- **Authors:** [YOU MUST COMPLETE THIS]',
        '- **DOI / URL:** [YOU MUST COMPLETE THIS]',
        '- **Date of deposit:** '
        f'{datetime.now().strftime("%Y-%m-%d")}',
        '- **Commit hash / version tag:** '
        '[YOU MUST COMPLETE THIS — e.g. git rev-parse HEAD]',
        '',
        '---',
        '',
        '## Study Overview',
        '',
        '[YOU MUST COMPLETE THIS — 2 to 5 sentences describing '
        'what this repository does and what paper it supports. '
        'This cannot be generated automatically.]',
        '',
        '---',
        '',
        '## System Requirements',
        '',
        '- **Operating system:** [e.g. Ubuntu 22.04 / macOS 13 '
        '/ Windows 11]',
        '- **Programming language:** [e.g. Python 3.11.2]',
        '- **RAM required:** [e.g. 16GB minimum]',
        '- **GPU required:** [Yes/No — if yes, specify model]',
        '- **Estimated runtime:** [e.g. 2 hours on 8-core laptop]',
        '- **HPC required:** [Yes/No — if yes, specify nodes/cores]',
        '',
        '---',
        '',
        '## Installation',
        '',
        '```bash',
        '# 1. Clone or download this repository',
        '# 2. Create a virtual environment',
        'python -m venv venv',
        'source venv/bin/activate  '
        '# Windows: venv\\Scripts\\activate',
        '',
        '# 3. Install dependencies',
        '# IMPORTANT: First add version numbers to '
        'requirements_DRAFT.txt',
        '# then rename it to requirements.txt',
        'pip install -r requirements.txt',
        '```',
        '',
        '[YOU MUST COMPLETE THIS — add any additional '
        'installation steps]',
        '',
        '---',
        '',
        '## Execution',
        '',
        '[YOU MUST COMPLETE THIS — describe the steps to run '
        'your analysis]',
        '',
        'See `QUICKSTART_DRAFT.md` for an inferred execution '
        'order (verify before using).',
        '',
        '---',
        '',
        '## Data',
        '',
        '- **Data location:** [describe where data files are]',
        '- **Data source:** [YOU MUST COMPLETE THIS]',
        '- **Data version:** [YOU MUST COMPLETE THIS — '
        'exact version/date of any external dataset]',
        '- **Anonymised/synthetic:** [Yes/No — if yes, '
        'describe transformation]',
        '',
        '---',
        '',
        '## Expected Outputs',
        '',
        '[YOU MUST COMPLETE THIS — describe what a validator '
        'should see after running your code]',
        '',
        '### Figure to file mapping',
        '',
        '[YOU MUST COMPLETE THIS — the tool cannot infer '
        'which scripts produce which figures]',
        '',
        '| Paper Figure | Generated File | Producing Script |',
        '|---|---|---|',
        '| Figure 1 | | |',
        '| Figure 2 | | |',
        '',
        '---',
        '',
        '## Definition of Successful Reproduction',
        '',
        '> ⚠️ **YOU MUST COMPLETE THIS SECTION.**',
        '> State exactly what constitutes successful reproduction.',
        '> Include numerical values and tolerance bands.',
        '',
        '[YOU MUST COMPLETE THIS]',
        '',
        '---',
        '',
        '## Known Issues and Limitations',
        '',
        '[YOU MUST COMPLETE THIS — document any platform '
        'sensitivity, stochasticity, or known reproduction '
        'limitations]',
        '',
        '---',
        '',
        '## Licence',
        '',
        'See `LICENCE_DRAFT.txt` (verify and rename to LICENCE).',
        '',
        '---',
        '',
        '## Contact',
        '',
        '[YOU MUST COMPLETE THIS — who should validators '
        'contact if reproduction fails?]',
        '',
        '---',
        '',
        f'*README_DRAFT.md generated by ValiChord Repository Readiness Check v15 — {now}*',
        '*Verify all content before removing _DRAFT from filename.*',
    ]

    # append original readme if it existed but was inadequate
    if existing_readme and len(existing_readme.strip()) > 50:
        lines += [
            '',
            '---',
            '',
            '## Original README Content (for reference)',
            '',
            '> The following is the original README content.',
            '> Use it to fill in the sections above.',
            '',
            existing_readme,
        ]

    out = output_dir / 'README_DRAFT.md'
    out.write_text('\n'.join(lines), encoding='utf-8-sig')
    print(f"  → README_DRAFT.md")


# ── requirements_DRAFT.txt ───────────────────────────────────────────────────

def _generate_requirements_draft(repo_dir, all_files,
                                   findings, output_dir):
    """Generate requirements_DRAFT.txt from import statements."""

    imports = set()

    import ast as _ast
    for f in all_files:
        if f.suffix.lower() == '.py':
            try:
                src = f.read_text(encoding='utf-8', errors='ignore')
                try:
                    tree = _ast.parse(src)
                    for node in _ast.walk(tree):
                        if isinstance(node, _ast.Import):
                            for alias in node.names:
                                imports.add(alias.name.split('.')[0])
                        elif isinstance(node, _ast.ImportFrom):
                            if node.module:
                                imports.add(node.module.split('.')[0])
                except SyntaxError:
                    for line in src.splitlines():
                        line = line.strip()
                        m = re.match(r'^import\s+([\w]+)', line)
                        if m:
                            imports.add(m.group(1))
                        m = re.match(r'^from\s+([\w]+)', line)
                        if m:
                            imports.add(m.group(1))
            except Exception:
                pass

    # filter out stdlib and local modules
    stdlib = {
        'os', 'sys', 're', 'math', 'json', 'csv', 'io',
        'time', 'datetime', 'pathlib', 'shutil', 'tempfile',
        'collections', 'itertools', 'functools', 'operator',
        'string', 'random', 'copy', 'abc', 'typing',
        'dataclasses', 'enum', 'warnings', 'logging',
        'unittest', 'subprocess', 'threading', 'multiprocessing',
        'argparse', 'configparser', 'hashlib', 'base64',
        'urllib', 'http', 'email', 'html', 'xml', 'sqlite3',
        'pickle', 'struct', 'array', 'queue', 'socket',
        'ssl', 'uuid', 'platform', 'inspect', 'importlib',
        'ast', 'dis', 'traceback', 'contextlib', 'weakref',
        'gc', 'ctypes', 'builtins', 'types', 'textwrap',
        'pprint', 'glob', 'fnmatch', 'stat', 'pwd', 'grp',
        'zipfile', 'tarfile', 'gzip', 'bz2', 'lzma',
        'zlib', 'binascii', 'codecs',
    }

    # local python files in repo
    local_modules = {
        f.stem.lower() for f in all_files
        if f.suffix.lower() == '.py'
    }

    external = sorted(
        imp for imp in imports
        if imp.lower() not in stdlib
        and imp.lower() not in local_modules
        and not imp.startswith('_')
    )

    now = datetime.now().strftime('%Y-%m-%d %H:%M')

    lines = [
        '# ============================================================',
        '# DEPENDENCY EXTRACTION NOTICE',
        '# Generated by ValiChord Repository Readiness Check v15',
        '#',
        '# These package names were inferred from import statements',
        '# by static analysis. This list is NOT authoritative.',
        '#',
        '# - Local module names have been excluded',
        '# - Standard library modules have been excluded',
        '# - ALL VERSION NUMBERS ARE UNKNOWN',
        '#   You must supply exact versions before this file',
        '#   can be used for reproduction',
        '# - This list may include optional or unused packages',
        '# - This list may miss dynamically imported packages',
        '#',
        f'# Generated: {now}',
        '# ============================================================',
        '',
    ]

    if external:
        for pkg in external:
            lines.append(f'{pkg}==UNKNOWN')
    else:
        lines += [
            '# No external imports detected.',
            '# Add your dependencies manually.',
        ]

    lines += [
        '',
        '# ============================================================',
        '# Local modules found in this repository (excluded above):',
    ]
    for m in sorted(local_modules):
        lines.append(f'# {m}')
    lines.append('# ============================================================')

    out = output_dir / 'requirements_DRAFT.txt'
    out.write_text('\n'.join(lines), encoding='utf-8-sig')
    print(f"  → requirements_DRAFT.txt "
          f"({len(external)} packages detected)")


# ── QUICKSTART_DRAFT.md ──────────────────────────────────────────────────────


def _install_instructions(code_files):
    """Return language-appropriate install instructions."""
    suffixes = {f.suffix.lower() for f in code_files}
    lines = []
    if '.jl' in suffixes:
        lines.append('3. Install dependencies: `julia --project=. -e "using Pkg; Pkg.instantiate()"`')
    if '.r' in suffixes or '.rmd' in suffixes:
        lines.append('3. Install R dependencies: `Rscript -e "renv::restore()"`')
    if '.do' in suffixes or '.ado' in suffixes:
        lines.append('3. Open Stata and run the master do-file listed above')
    if '.m' in suffixes:
        lines.append('3. Open MATLAB and run the master script listed above')
    if '.py' in suffixes or not lines:
        lines.append('3. Install dependencies: `pip install -r requirements.txt`')
    return lines

def _generate_quickstart_draft(repo_dir, all_files,
                                 findings, output_dir):
    """Generate QUICKSTART_DRAFT.md with inferred execution order."""

    now = datetime.now().strftime('%Y-%m-%d %H:%M')

    code_files = [
        f for f in all_files
        if f.suffix.lower() in CODE_EXTENSIONS
    ]

    # try to find numbered scripts
    numbered = []
    for f in code_files:
        m = re.match(r'^(0*)([0-9]+)[_\-](.+)', f.name)
        if m:
            numbered.append((int(m.group(2)), f))
    numbered.sort(key=lambda x: x[0])

    lines = [
        '# ValiChord Repository Readiness Check — Quick Start',
        '',
        '> ⚠️ **IMPORTANT — THIS EXECUTION ORDER IS INFERRED**',
        '> **AND HAS NOT BEEN VALIDATED.**',
        '> ',
        '> The script order below was generated by automated',
        '> analysis and may be incorrect. Do not rely on it',
        '> without manual verification against your own',
        '> knowledge of the pipeline.',
        '> ',
        '> **Confidence level: LOW**',
        '',
        '---',
        '',
    ]

    if numbered:
        lines += [
            '## Inferred Execution Order',
            '(from numbered script filenames)',
            '',
        ]
        for num, f in numbered:
            rel = f.relative_to(repo_dir)
            lines.append(f'{num}. `{rel}`')
        lines.append('')
    else:
        lines += [
            '## Script Files Found',
            '',
            'No numbered scripts detected. '
            'The following scripts were found — ',
            'you must specify the correct execution order:',
            '',
        ]
        for f in sorted(code_files, key=lambda x: x.name):
            rel = f.relative_to(repo_dir)
            lines.append(f'- `{rel}`')
        lines.append('')

    lines += [
        '---',
        '',
        '## Before Running',
        '',
        '1. Complete `README_DRAFT.md` and rename to `README.md`',
        '2. Add version numbers to `requirements_DRAFT.txt` '
        'and rename to `requirements.txt`',
        *_install_instructions(code_files),
        '4. Test on a **clean machine** — not just a new folder '
        'on your development machine',
        '',
        '---',
        '',
        f'*Generated by ValiChord Repository Readiness Check v15 — {now}*',
    ]

    out = output_dir / 'QUICKSTART_DRAFT.md'
    out.write_text('\n'.join(lines), encoding='utf-8-sig')
    print(f"  → QUICKSTART_DRAFT.md")


# ── LICENCE_DRAFT.txt ────────────────────────────────────────────────────────

def _generate_licence_draft(output_dir):
    """Generate LICENCE_DRAFT.txt."""

    now = datetime.now().strftime('%Y-%m-%d %H:%M')
    year = datetime.now().year

    content = f"""LICENCE_DRAFT.txt — generated by ValiChord Repository Readiness Check v15
Generated: {now}

YOU MUST COMPLETE THIS FILE before sharing your repository.

Choose one of the following options and replace this entire
file with your chosen licence text.

============================================================
RECOMMENDED FOR CODE: MIT Licence
============================================================

MIT License

Copyright (c) {year} [YOUR NAME]

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or
sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.

============================================================
RECOMMENDED FOR DATA: Creative Commons CC-BY 4.0
============================================================

If your repository includes data, consider licensing it under
Creative Commons Attribution 4.0 International (CC-BY 4.0).

See: https://creativecommons.org/licenses/by/4.0/

============================================================
IMPORTANT QUESTIONS TO ANSWER BEFORE CHOOSING:
============================================================

1. Does your data include human subjects data?
   If yes: do you have authorisation to share it?

2. Does your code use any GPL-licensed libraries?
   If yes: your code may need to be GPL-licensed too.

3. Does your institution have a default IP policy?
   If yes: check whether you need institutional approval.

4. Does your funder require a specific open licence?
   If yes: use that licence.

============================================================
Rename this file to LICENCE (no extension) or LICENCE.md
after completing it.
============================================================
"""

    out = output_dir / 'LICENCE_DRAFT.txt'
    out.write_text(content, encoding='utf-8-sig')
    print(f"  → LICENCE_DRAFT.txt")


# ── README placeholder ───────────────────────────────────────────────────────


def generate_proposed_corrections(repo_dir, all_files, findings, output_dir):
    """Generate corrected file copies in /proposed_corrections/."""

    corrections_dir = output_dir / 'proposed_corrections'
    corrections_dir.mkdir(exist_ok=True)

    # get all [C] absolute path findings
    path_findings = [f for f in findings if f['mode'] == 'C']

    if not path_findings:
        return

    # write a README for the corrections folder
    readme_lines = [
        '# proposed_corrections/',
        '',
        '> ⚠️ **THESE FILES CONTAIN A DELIBERATE RUNTIME ERROR.**',
        '> They will not execute until you remove the error block',
        '> at the top of each file.',
        '>',
        '> This is intentional. You must review each correction',
        '> before using it. The tool cannot guarantee that the',
        '> relative path replacements are correct for your setup.',
        '',
        '## How to use these files',
        '',
        '1. Open each file and read the correction at the top',
        '2. Verify the relative path is correct for your directory structure',
        '3. Remove the `raise RuntimeError` block at the top',
        '4. Replace the corresponding file in your repository',
        '5. Test that your code still runs correctly',
        '',
        '## Files corrected',
        '',
    ]

    corrected_files = []

    for path_finding in path_findings:
        # extract filename from evidence
        evidence = path_finding.get('evidence', [])
        if not evidence:
            continue

        fname = path_finding['detail']
        # find the actual file
        target_files = [
            f for f in all_files
            if path_finding['evidence'][0].startswith(
                f'Evidence: {f.name}'
            )
        ]

        if not target_files:
            continue

        src_file = target_files[0]

        try:
            content = src_file.read_text(encoding='utf-8', errors='ignore')
        except Exception:
            continue

        # find and replace absolute paths
        abs_pattern = re.compile(
            r'(/Users/[a-zA-Z][a-zA-Z0-9_\-]{1,}/[^\s\'")\]]*)'
            r'|(/home/[a-zA-Z][a-zA-Z0-9_\-]{1,}/[^\s\'")\]]*)'
            r'|(/root/[a-zA-Z][^\s\'")\]]*)'
            r'|([A-Z]:\\\\[A-Za-z][^\s\'")\]]*)'
            r'|([A-Z]:/[A-Za-z][^\s\'")\]]*)'
        )

        matches = abs_pattern.findall(content)
        flat_matches = [m for group in matches for m in group if m]

        if not flat_matches:
            continue

        corrected = content
        replacements = []

        for match in flat_matches:
            # generate a relative path suggestion
            # extract just the filename/last component
            parts = match.replace('\\', '/').rstrip('/').split('/')
            suggested = './data/' + parts[-1] if parts else './data/file'
            corrected = corrected.replace(match, suggested, 1)
            replacements.append((match, suggested))

        # build the warning block
        warning_lines = [
            '# ============================================================',
            '# VALICHORD PROPOSED CORRECTION — DO NOT RUN WITHOUT REVIEWING',
            '# ============================================================',
            '# This file was generated by ValiChord Repository Readiness Check.',
            '# The following absolute paths were detected and replaced',
            '# with suggested relative paths:',
            '#',
        ]
        for orig, sugg in replacements:
            warning_lines.append(f'#   ORIGINAL:  {orig}')
            warning_lines.append(f'#   SUGGESTED: {sugg}')
            warning_lines.append('#')
        warning_lines += [
            '# VERIFY each replacement before using this file.',
            '# The suggested paths may not match your directory structure.',
            '# ============================================================',
            '',
            'raise RuntimeError(',
            '    "VALICHORD PROPOSED CORRECTION: Remove this error block "',
            '    "after verifying the path corrections above."',
            ')',
            '',
            '# ============================================================',
            '',
        ]

        warning_block = '\n'.join(warning_lines) + '\n'
        final_content = warning_block + corrected

        out_file = corrections_dir / src_file.name
        out_file.write_text(final_content, encoding='utf-8-sig')
        corrected_files.append(src_file.name)

    # write the corrections README
    for fname in corrected_files:
        readme_lines.append(f'- `{fname}`')

    readme_lines += [
        '',
        '---',
        '',
        f'*Generated by ValiChord Repository Readiness Check v15*',
    ]

    readme_out = corrections_dir / 'README.md'
    readme_out.write_text('\n'.join(readme_lines), encoding='utf-8-sig')

    print(f"  → proposed_corrections/ ({len(corrected_files)} files)")