"""
ValiChord Auto-Generate
Draft File Generator
Produces all _DRAFT output files per ValiChord Specification v15
"""

from pathlib import Path
import re
from datetime import datetime


CODE_EXTENSIONS = {
    '.py', '.r', '.rmd', '.qmd', '.jl', '.m', '.sh', '.bash', '.smk', '.nf', '.groovy',
    '.do', '.sas', '.ado', '.c', '.cpp', '.f', '.f90',
    '.sql', '.rs', '.go', '.java', '.js', '.ts'
}

NOTEBOOK_EXTENSIONS = {'.ipynb', '.mlx', '.rmd', '.qmd'}

# Gretl script/model files — classified as Code in inventory but not subject to
# pip/conda dependency checks (Gretl manages its own environment)
GRETL_EXTENSIONS = {'.inp', '.gfn'}

_ALL_CODE_EXTENSIONS = CODE_EXTENSIONS | GRETL_EXTENSIONS

README_NAMES = {'readme.md', 'readme.txt', 'readme.rst', 'readme'}

DEPENDENCY_FILES = {
    'requirements.txt', 'requirements_extra.txt', 'environment.yml', 'environment.yaml',
    'pipfile.lock', 'poetry.lock', 'setup.py', 'pyproject.toml',
    'renv.lock', 'cargo.toml', 'package.json'
}


def generate_all_drafts(repo_dir, all_files, findings, output_dir):
    """Generate all _DRAFT files."""

    modes_found = {f['mode'] for f in findings}

    has_code = any(f.suffix.lower() in CODE_EXTENSIONS or f.suffix.lower() in {'.ipynb', '.nf'} for f in all_files)
    _generate_inventory(repo_dir, all_files, output_dir)
    _generate_readme_draft(repo_dir, all_files, findings, output_dir)
    if has_code:
        _generate_requirements_draft(repo_dir, all_files,
                                      findings, output_dir)
        _generate_quickstart_draft(repo_dir, all_files,
                                    findings, output_dir)
    _licence_names = {'licence', 'license', 'licence.md', 'license.md',
                      'licence.txt', 'license.txt', 'copying', 'copying.md'}
    _has_licence = any(f.name.lower() in _licence_names for f in all_files)
    if not _has_licence:
        _generate_licence_draft(output_dir, all_files)
    generate_proposed_corrections(repo_dir, all_files, findings, output_dir)


# ── INVENTORY_DRAFT.md ───────────────────────────────────────────────────────

def _generate_inventory(repo_dir, all_files, output_dir):
    """Generate INVENTORY_DRAFT.md — full file listing."""

    now = datetime.now().strftime('%Y-%m-%d %H:%M')
    lines = [
        '# ValiChord Repository Readiness Check — File Inventory',
        '',
        f'**Generated:** {now}',
        f'**Total files:** {len(all_files)}',
        '',
        '> This inventory was generated by automated analysis.',
        '> File purpose descriptions are structural only — '
        'derived from',
        '> code evidence where available. Semantic descriptions',
        '> are not inferred from filenames.',
        '',
        '---',
        '',
        '## File Listing',
        '',
        '| File | Type | Size | Notes |',
        '|---|---|---|---|',
    ]

    for f in sorted(all_files, key=lambda x: str(x)):
        rel = f.relative_to(repo_dir)
        size = f.stat().st_size
        size_str = (f'{size:,} bytes' if size < 10240
                    else f'{size/1024:.1f} KB')
        ftype = _classify_file(f)
        notes = _file_notes(f)
        lines.append(f'| `{rel}` | {ftype} | {size_str} | {notes} |')

    lines += [
        '',
        '---',
        '',
        f'*Generated by ValiChord Repository Readiness Check — v15 — {now}*',
    ]

    out = output_dir / 'INVENTORY_DRAFT.md'
    out.write_text('\n'.join(lines), encoding='utf-8-sig')
    print(f"  → INVENTORY_DRAFT.md ({len(all_files)} files)")


def _is_model_artifact_file(f):
    """Return True if this file is a trained model binary or model config, not research data."""
    _model_name_indicators = {'model', 'clf', 'classifier', 'regressor', 'estimator',
                              'pipeline', 'weights', 'tokenizer', 'vocab', 'checkpoint'}
    _model_dirs = {'models', 'model', 'checkpoints', 'saved_model'}
    name_lower = f.name.lower()
    ext = f.suffix.lower()
    in_model_dir = any(part.lower() in _model_dirs for part in f.parts)
    has_model_name = any(ind in name_lower for ind in _model_name_indicators)
    if ext in {'.pkl', '.pickle', '.pt', '.pth', '.onnx', '.safetensors', '.bin'}:
        return has_model_name or in_model_dir
    if ext == '.json':
        return (has_model_name or in_model_dir)
    return False


def _classify_file(f):
    ext = f.suffix.lower()
    if ext in _ALL_CODE_EXTENSIONS:
        return 'Code'
    if ext in NOTEBOOK_EXTENSIONS:
        return 'Notebook'
    if ext in {'.md', '.txt', '.rst', '.html', '.tex'}:
        return 'Documentation'
    if _is_model_artifact_file(f):
        return 'Model artifact'
    if ext in {'.csv', '.tsv', '.xlsx', '.json', '.parquet',
               '.rds', '.rdata', '.dta', '.sav', '.mat',
               '.pkl', '.npy', '.npz', '.hdf5', '.h5', '.gdt'}:
        return 'Data'
    if ext in {'.png', '.jpg', '.jpeg', '.pdf', '.svg', '.tif'}:
        return 'Figure/Image'
    if f.name.lower() == 'citation.cff':
        return 'Citation'
    if f.name.lower() in DEPENDENCY_FILES:
        return 'Dependency spec'
    if ext in {'.yml', '.yaml', '.toml', '.ini', '.cfg'}:
        return 'Configuration'
    if ext in {'.sh', '.bash'}:
        return 'Shell script'
    if ext in {'.gpg', '.enc', '.secret', '.age', '.asc'}:
        return '⚠️ POSSIBLY ENCRYPTED'
    if f.name == 'Snakefile' or f.suffix.lower() == '.smk':
        return 'Workflow'
    return 'Other'


def _file_notes(f):
    name = f.name.lower()
    ext = f.suffix.lower()
    if ext in {'.gpg', '.enc', '.secret', '.age', '.asc'}:
        return '🔴 POSSIBLY ENCRYPTED — may be unusable without key'
    if name == 'citation.cff':
        return 'CITATION.cff — check all required fields are complete'
    if 'codebook' in name or 'data_dictionary' in name or 'data_dict' in name:
        return 'Codebook / data dictionary'
    if name in README_NAMES:
        return 'README'
    if name in {'licence', 'license', 'licence.md',
                'license.md', 'licence.txt', 'license.txt'}:
        return 'Licence file'
    import re as _ren
    if _ren.match(r'requirements.*\.txt$', name):
        return 'Dependency specification'
    if name == 'dockerfile':
        return 'Container definition'
    if re.match(r'^(\d+)(?:[.\-](\d+))?(?:[_\-]|\.(?!\d))', f.name):
        return 'Numbered script — execution order implied'
    return ''


# ── README_DRAFT.md ──────────────────────────────────────────────────────────


def _readme_install_block(all_files, r_packages=None, github_pkgs=None):
    """Return language-appropriate installation instructions for README_DRAFT."""
    if github_pkgs is None:
        github_pkgs = {}
    suffixes = {f.suffix.lower() for f in all_files}
    if any(f.name == 'Snakefile' for f in all_files):
        suffixes.add('.smk')
    names = {f.name.lower() for f in all_files}
    # data-only deposit — no code present
    has_code = any(s in suffixes for s in {".py", ".r", ".jl", ".do", ".m", ".rmd", ".smk", ".ipynb", ".nf", ".groovy"})
    if not has_code:
        codebook = next((f.name for f in all_files if "codebook" in f.name.lower() or "data_dict" in f.name.lower()), None)
        return [
            "# This is a data-only deposit. No code execution is required.",
            "# Files are provided in standard formats (CSV, Excel, etc.)",
            f"# See {codebook} for variable descriptions." if codebook else "# See the codebook for variable descriptions.",
        ]
    # conda repo — takes precedence over all language-specific checks
    if 'environment.yml' in names or 'environment.yaml' in names:
        env_file = 'environment.yml' if 'environment.yml' in names else 'environment.yaml'
        env_name = 'myenv'
        env_path = min((f for f in all_files if f.name.lower() == env_file),
                       key=lambda x: len(x.parts), default=None)
        if env_path:
            import re as _re
            m = _re.search(r'^name:\s*(\S+)', env_path.read_text(encoding='utf-8', errors='ignore'), _re.MULTILINE)
            if m:
                env_name = m.group(1)
        return [
            '# 1. Clone or download this repository',
            '# 2. Create and activate the conda environment',
            f'conda env create -f {env_file}',
            f'conda activate {env_name}',
        ]
    # Docker repo — takes priority over language-specific blocks
    if 'dockerfile' in names:
        return [
            '# 1. Build the Docker image',
            'docker build -t my-analysis .',
            '# 2. Run the container (mount data directory)',
            'docker run -v $(pwd)/data:/app/data my-analysis',
            '# Or with an interactive shell:',
            '# docker run -it -v $(pwd)/data:/app/data my-analysis bash',
        ]
    if '.jl' in suffixes:
        if 'project.toml' in names:
            return [
                '# 1. Clone or download this repository',
                '# 2. Install Julia dependencies',
                'julia --project=. -e "using Pkg; Pkg.instantiate()"',
            ]
        else:
            # Check for embedded Pluto manifest — if present, just open in Pluto
            pluto_files = [f for f in all_files if f.suffix.lower() == '.jl']
            has_pluto_deps = any(
                'PLUTO_PROJECT_TOML_CONTENTS' in f.read_text(encoding='utf-8', errors='ignore')
                for f in pluto_files
            )
            if has_pluto_deps:
                return [
                    '# 1. Clone or download this repository',
                    '# 2. Open the notebook in Pluto — dependencies are embedded',
                    '# julia -e \'using Pkg; Pkg.add(\"Pluto\"); using Pluto; Pluto.run()\'',
                    '# Then open the .jl notebook file — Pluto will install dependencies automatically',
                ]
            # No Pluto, no Project.toml — extract packages dynamically
            import re as _re
            julia_stdlib_set = {'Random','Statistics','LinearAlgebra','Dates','Printf',
                                'Base','Core','Main','Pkg','Test','Logging','REPL',
                                'InteractiveUtils','Distributed','Serialization',
                                'Markdown','Unicode','DelimitedFiles','SparseArrays'}
            jl_pkgs = sorted({
                pkg.strip()
                for f in pluto_files
                for line in f.read_text(encoding='utf-8', errors='ignore').splitlines()
                for m in [_re.match(r'^using\s+([\w,\s]+)', line.strip())]
                if m
                for pkg in _re.split(r'[,\s]+', m.group(1))
                if pkg.strip() and pkg.strip() not in julia_stdlib_set
            })
            if jl_pkgs:
                pkg_list = ', '.join(f'\"{p}\"' for p in jl_pkgs)
                return [
                    '# 1. Clone or download this repository',
                    '# 2. Create Project.toml and Manifest.toml (recommended):',
                    f'#    julia --project=. -e \'using Pkg; Pkg.add([{pkg_list}]); Pkg.resolve()\'',
                    '#    Then commit Project.toml and Manifest.toml',
                    '# Or to install without pinning (not recommended for reproducibility):',
                    f'#    julia -e \'using Pkg; Pkg.add([{pkg_list}])\'',
                ]
            return ['2. Create Project.toml and Manifest.toml to pin package versions.',
                    '   Run: julia --project=. -e "using Pkg; Pkg.add([\"PackageName\"]); Pkg.resolve()"  ',
                    '   Then commit Project.toml and Manifest.toml']
    if '.r' in suffixes or '.rmd' in suffixes:
        has_python = '.py' in suffixes
        if 'renv.lock' in names:
            if has_python:
                return [
                    '# 1. Clone or download this repository',
                    '# 2. Set up Python environment',
                    'python -m venv venv',
                    'source venv/bin/activate  # Windows: venv\\Scripts\\activate',
                    'pip install -r requirements.txt',
                    '# 3. Restore R environment',
                    'Rscript -e "renv::restore()"',
                ]
            return [
                '# 1. Clone or download this repository',
                '# 2. Restore R environment',
                'Rscript -e "renv::restore()"',
            ]
        pkgs = r_packages or ['dplyr', 'ggplot2']
        cran_pkgs = [p for p in pkgs if p.lower() not in github_pkgs]
        gh_only = [p for p in pkgs if p.lower() in github_pkgs]
        pkg_str = ', '.join("'" + p + "'" for p in cran_pkgs) if cran_pkgs else None
        gh_lines = [f"Rscript -e \"devtools::install_github('{github_pkgs.get(p.lower(), p).strip(chr(39)).strip(chr(34))}')\"" for p in gh_only]
        block = ['# 1. Clone or download this repository']
        if has_python:
            block += ['# 2. Set up Python environment',
                      'python -m venv venv',
                      'source venv/bin/activate  # Windows: venv\\Scripts\\activate',
                      'pip install -r requirements.txt']
            step = 3
        else:
            step = 2
        if pkg_str:
            block.append(f'# {step}. Install CRAN packages')
            block.append(f'Rscript -e "install.packages(c({pkg_str}))"')
            step += 1
        if gh_lines:
            block.append(f'# {step}. Install GitHub packages')
            block += gh_lines
        return block
    if '.do' in suffixes or '.ado' in suffixes:
        return [
            '# 1. Clone or download this repository',
            '# 2. Install required Stata packages via ssc install',
        ]
    if '.m' in suffixes:
        eeglab_fns = {'pop_epoch', 'pop_autorej', 'pop_resample', 'pop_eegfiltnew',
                      'eeglab', 'pop_loadset', 'pop_saveset', 'runica'}
        has_eeglab = any(
            any(fn in f.read_text(encoding='utf-8', errors='ignore') for fn in eeglab_fns)
            for f in all_files if f.suffix.lower() == '.m'
        )
        block = [
            '# 1. Open MATLAB (see README for required version)',
            '# 2. Ensure required toolboxes are licensed and installed',
        ]
        if has_eeglab:
            block += [
                '# 3. Add EEGLAB folder to your MATLAB path',
                '#    addpath(genpath("/path/to/eeglab"))',
                '# 4. Open and run the main script',
            ]
        else:
            block.append('# 3. Open and run the main script')
        return block
    # conda repo — environment.yml present
    if 'environment.yml' in names or 'environment.yaml' in names:
        env_file = 'environment.yml' if 'environment.yml' in names else 'environment.yaml'
        # Try to extract conda env name
        env_name = 'myenv'
        env_path = min((f for f in all_files if f.name.lower() == env_file),
                       key=lambda x: len(x.parts), default=None)
        if env_path:
            import re as _re
            m = _re.search(r'^name:\s*(\S+)', env_path.read_text(encoding='utf-8', errors='ignore'), _re.MULTILINE)
            if m:
                env_name = m.group(1)
        return [
            '# 1. Clone or download this repository',
            '# 2. Create and activate the conda environment',
            f'conda env create -f {env_file}',
            f'conda activate {env_name}',
        ]
    # Nextflow pipeline
    if '.nf' in suffixes or any(f.name.lower() == 'main.nf' for f in all_files):
        return [
            '# 1. Clone or download this repository',
            '# 2. Install Nextflow (if not already installed)',
            'curl -s https://get.nextflow.io | bash',
            '# Or via conda: conda install -c bioconda nextflow',
        ]
    # default Python
    import re as _re_iblk
    _data_url_pat = _re_iblk.compile(
        r'https?://(?:zenodo\.org|figshare\.com|osf\.io|datadryad\.org'  
        r'|dataverse\.harvard\.edu|data\.mendeley\.com)',
        _re_iblk.IGNORECASE)
    _has_external_data = any(
        _data_url_pat.search(f.read_text(encoding='utf-8', errors='ignore'))
        for f in all_files if f.name.lower() in {'readme.md','readme.txt','readme.rst'})
    return [
        *(['# 0. Download required data',
           '# [YOU MUST COMPLETE — add wget/curl or manual download instructions]',
           '# Example: wget -O data/dataset.tif https://zenodo.org/record/.../files/dataset.tif',
           '# Verify checksum: sha256sum data/dataset.tif',
           ''] if _has_external_data else []),
        '# 1. Clone or download this repository',
        '# 2. Create a virtual environment',
        'python -m venv venv',
        'source venv/bin/activate  # Windows: venv\\Scripts\\activate',
        '',
        '# 3. Install dependencies',
        '# First ensure all version numbers are pinned in requirements.txt',
        'pip install -r requirements.txt',
    ]

def _generate_readme_draft(repo_dir, all_files, findings, output_dir):
    """Generate README_DRAFT.md."""

    now = datetime.now().strftime('%Y-%m-%d %H:%M')

    # try to find existing readme content — prefer root-level README over subfolder
    existing_readme = ''
    existing_readme_file = None
    for f in sorted(all_files, key=lambda x: len(x.relative_to(repo_dir).parts)):
        if f.name.lower() in README_NAMES:
            try:
                existing_readme = f.read_text(encoding='utf-8', errors='ignore')
                existing_readme_file = f
            except Exception:
                pass
            break  # sorted by depth, so first match is shallowest

    # assess whether existing readme is adequate
    readme_adequate = False
    if existing_readme and len(existing_readme.strip()) > 500:
        key_sections = [
            'installation', 'usage', 'data', 'run', 'reproduce',
            'requirement', 'depend', 'import', 'abstract', 'author',
            'method', 'result', 'how to', 'getting started', 'setup',
        ]
        sections_found = sum(1 for s in key_sections if s in existing_readme.lower())
        if sections_found >= 2:
            readme_adequate = True

    if readme_adequate:
        # existing README is reasonable — just note what's missing.
        # Exclude [A] "no readme" findings since we did find one to show.
        readme_findings = [f for f in findings
                           if f.get('mode') in ('A', 'G', 'Z', 'K', 'N', 'E', 'Y')
                           and 'No README file found' not in f.get('title', '')]
        lines = [
            '# README Review Notes',
            '',
            '> ⚠️ **README_DRAFT.md** — Your existing README appears adequate.',
            '> This file only lists items that may need attention.',
            '> Your original README has been preserved — do not replace it with this file.',
            '',
            '---',
            '',
            '## Items to check in your existing README',
            '',
        ]
        if readme_findings:
            for f in readme_findings:
                lines.append(f'- {f.get("title", "")}')
        else:
            lines.append('- No specific README gaps detected.')
        lines += [
            '',
            '---',
            '',
            '## Your existing README (for reference)',
            '',
            existing_readme,
        ]
        out = output_dir / 'README_DRAFT.md'
        out.write_text('\n'.join(lines), encoding='utf-8-sig')
        print(f"  → README_DRAFT.md (existing README adequate)")
        return

    # extract R packages for install block
    r_pkgs = set()
    github_pkgs = {}  # pkg_name_lower -> 'owner/repo'
    lib_pat = re.compile(r'(?:library|require)\s*\(\s*["\']?([\w\.]+)["\']?\s*\)')
    vec_pkg_pat = re.compile(r'(?i)(?:packages?|pkgs?)\s*<-\s*c\s*\(([^)]+)\)')
    github_pat = re.compile(r'(?:devtools|remotes)::install_github\s*\(\s*["\']([^"\'/]+/([\w.-]+))["\']', re.IGNORECASE)
    for rf in [f for f in all_files if f.suffix.lower() in {'.r', '.rmd', '.qmd'}]:
        src = rf.read_text(encoding='utf-8', errors='ignore')
        for m in lib_pat.finditer(src):
            r_pkgs.add(m.group(1))
        for m in vec_pkg_pat.finditer(src):
            for pkg in re.findall(r'["\']+([\w\.]+)["\']', m.group(1)):
                r_pkgs.add(pkg)
    for rf in all_files:
        if re.match(r'(install|setup).*\.r$', rf.name.lower()):
            try:
                src = rf.read_text(encoding='utf-8', errors='ignore')
                for m in github_pat.finditer(src):
                    github_pkgs[m.group(2).lower()] = m.group(1)
            except Exception:
                pass
    has_code = any(f.suffix.lower() in CODE_EXTENSIONS or f.suffix.lower() in {'.ipynb', '.nf'} or f.name in {'Snakefile', 'main.nf'} for f in all_files)
    if not has_code:
        # data-only deposit — use data-focused template
        data_files = [f for f in all_files if f.suffix.lower() in {".csv", ".tsv", ".xlsx", ".xls", ".dta", ".sav", ".json", ".parquet", ".mat", ".npy", ".npz", ".hdf5", ".h5", ".nc", ".feather", ".arrow", ".dif", ".rds", ".rdata"}]
        codebook = next((f.name for f in all_files if "codebook" in f.name.lower() or "data_dict" in f.name.lower()), None)
        lines = [
            '# [TITLE OF DATASET — YOU MUST COMPLETE THIS]',
            '',
            '> ⚠️ **README_DRAFT.md** — Generated by ValiChord. Complete all sections then rename to `README.md`.',
            '',
            '---',
            '',
            '## Dataset Identification',
            '',
            '- **Dataset title:** [YOU MUST COMPLETE THIS]',
            '- **Authors/collectors:** [YOU MUST COMPLETE THIS]',
            '- **Associated paper DOI:** [YOU MUST COMPLETE THIS]',
            '- **Date of deposit:** ' + datetime.now().strftime('%Y-%m-%d'),
            '- **Licence:** [e.g. CC BY 4.0]',
            '',
            '---',
            '',
            '## Dataset Overview',
            '',
            '[YOU MUST COMPLETE THIS — describe what this dataset contains, how it was collected, and what research it supports.]',
            '',
            '---',
            '',
            '## Data Files',
            '',
            '| File | Format | Description | Rows | Variables |',
            '|---|---|---|---|---|',
            *[f'| `{f.name}` | {f.suffix.upper().lstrip(".")} | [YOU MUST COMPLETE THIS] | | |' for f in data_files],
            '',
            '---',
            '',
            '## Variables',
            '',
            f'See `{codebook}` for full variable descriptions.' if codebook else '[YOU MUST COMPLETE THIS — list all variables or reference your codebook.]',
            '',
            '---',
            '',
            '## Collection Methodology',
            '',
            '[YOU MUST COMPLETE THIS — describe how data was collected, survey instruments, sampling strategy, dates of collection.]',
            '',
            '---',
            '',
            '## Access Conditions',
            '',
            '[YOU MUST COMPLETE THIS — state whether data is open access, restricted, or embargoed. If restricted, who to contact.]',
            '',
            '---',
            '',
            '## File Integrity',
            '',
            '[YOU MUST COMPLETE THIS — provide SHA-256 checksums for all data files.]',
            '',
            '| File | SHA-256 |',
            '|---|---|',
            *[f'| `{f.name}` | [checksum] |' for f in data_files],
            '',
            '---',
            '',
            f'*Generated by ValiChord Repository Readiness Check — {datetime.now().strftime("%Y-%m-%d %H:%M")}*',
        ]
        if existing_readme:
            lines += ["", "---", "", "## Original README (for reference)", "", existing_readme]
        out = output_dir / "README_DRAFT.md"
        out.write_text("\n".join(lines), encoding="utf-8-sig")
        print("  → README_DRAFT.md (data-only template)")
        return
    lines = [
        '# [TITLE OF PAPER — YOU MUST COMPLETE THIS]',
        '',
        '> ⚠️ **README_DRAFT.md** — This file was generated by '
        'ValiChord Repository Readiness Check.',
        '> All sections marked [YOU MUST COMPLETE THIS] require '
        'your input.',
        '> Verify all content, then rename to `README.md`.',
        '',
        '---',
        '',
        '## Study Identification',
        '',
        '- **Paper title:** [YOU MUST COMPLETE THIS]',
        '- **Authors:** [YOU MUST COMPLETE THIS]',
        '- **DOI / URL:** [YOU MUST COMPLETE THIS]',
        '- **Date of deposit:** '
        f'{datetime.now().strftime("%Y-%m-%d")}',
        '- **Commit hash / version tag:** '
        '[YOU MUST COMPLETE THIS — e.g. git rev-parse HEAD]',
        '',
        '---',
        '',
        '## Study Overview',
        '',
        '[YOU MUST COMPLETE THIS — 2 to 5 sentences describing '
        'what this repository does and what paper it supports. '
        'This cannot be generated automatically.]',
        '',
        '---',
        '',
        '## System Requirements',
        '',
        '- **Operating system:** [e.g. Ubuntu 22.04 / macOS 13 '
        '/ Windows 11]',
        '- **Programming language:** [e.g. Python 3.11.2]',
        '- **RAM required:** [e.g. 16GB minimum]',
        '- **GPU required:** [Yes/No — if yes, specify model]',
        '- **Estimated runtime:** [e.g. 2 hours on 8-core laptop]',
        '- **HPC required:** [Yes/No — if yes, specify nodes/cores]',
        '',
        '---',
        '',
        '## Installation',
        '',
        '```bash',
        *_readme_install_block(all_files, sorted(r_pkgs) if r_pkgs else None, github_pkgs=github_pkgs),
        '```',
        '',
        '[YOU MUST COMPLETE THIS — add any additional '
        'installation steps]',
        '',
        '---',
        '',
        '## Execution',
        '',
        '[YOU MUST COMPLETE THIS — describe the steps to run '
        'your analysis]',
        '',
        'See `QUICKSTART_DRAFT.md` for an inferred execution '
        'order (verify before using).',
        '',
        '---',
        '',
        '## Data',
        '',
        '- **Data location:** [describe where data files are]',
        '- **Data source:** [YOU MUST COMPLETE THIS]',
        '- **Data version:** [YOU MUST COMPLETE THIS — '
        'exact version/date of any external dataset]',
        '- **Anonymised/synthetic:** [Yes/No — if yes, '
        'describe transformation]',
        '',
        '---',
        '',
        '## Expected Outputs',
        '',
        '[YOU MUST COMPLETE THIS — describe what a validator '
        'should see after running your code]',
        '',
        '### Figure to file mapping',
        '',
        '[YOU MUST COMPLETE THIS — the tool cannot infer '
        'which scripts produce which figures]',
        '',
        '| Paper Figure | Generated File | Producing Script |',
        '|---|---|---|',
        '| Figure 1 | | |',
        '| Figure 2 | | |',
        '',
        '---',
        '',
        '## Definition of Successful Reproduction',
        '',
        '> ⚠️ **YOU MUST COMPLETE THIS SECTION.**',
        '> State exactly what constitutes successful reproduction.',
        '> Include numerical values and tolerance bands.',
        '',
        '[YOU MUST COMPLETE THIS]',
        '',
        '---',
        '',
        '## Known Issues and Limitations',
        '',
        '[YOU MUST COMPLETE THIS — document any platform '
        'sensitivity, stochasticity, or known reproduction '
        'limitations]',
        '',
        '---',
        '',
        '## Licence',
        '',
        'See `LICENCE_DRAFT.txt` (verify and rename to LICENCE).',
        '',
        '---',
        '',
        '## Contact',
        '',
        '[YOU MUST COMPLETE THIS — who should validators '
        'contact if reproduction fails?]',
        '',
        '---',
        '',
        f'*README_DRAFT.md generated by ValiChord Repository Readiness Check v15 — {now}*',
        '*Verify all content before removing _DRAFT from filename.*',
    ]

    # append original readme if it existed but was inadequate
    if existing_readme and len(existing_readme.strip()) > 50:
        lines += [
            '',
            '---',
            '',
            '## Original README Content (for reference)',
            '',
            '> The following is the original README content.',
            '> Use it to fill in the sections above.',
            '',
            existing_readme,
        ]

    out = output_dir / 'README_DRAFT.md'
    out.write_text('\n'.join(lines), encoding='utf-8-sig')
    print(f"  → README_DRAFT.md")


# ── requirements_DRAFT.txt ───────────────────────────────────────────────────

def _generate_requirements_draft(repo_dir, all_files,
                                   findings, output_dir):
    """Generate requirements_DRAFT.txt from import statements."""

    # preserve existing requirements_DRAFT.txt from prior run
    prior_draft = next((f for f in all_files if f.name.lower() == "requirements_draft.txt"), None)
    if prior_draft:
        prior_content = prior_draft.read_text(encoding="utf-8", errors="ignore")
        out = output_dir / "requirements_DRAFT.txt"
        out.write_text(
            "# Prior requirements_DRAFT.txt preserved from previous ValiChord run.\n"
            "# Review and pin all versions before renaming to requirements.txt.\n"
            "#\n" + prior_content, encoding="utf-8-sig")
        print("  -> requirements_DRAFT.txt (preserved from prior run)")
        return
    # Collect all requirements*.txt files to handle requirements_extra.txt etc.
    import re as _re2
    req_files_all = sorted(
        [f for f in all_files if _re2.match(r'requirements.*\.txt$', f.name.lower())],
        key=lambda x: x.name
    )
    if req_files_all:
        combined_lines = []
        for rf in req_files_all:
            try:
                rf_lines = rf.read_text(encoding='utf-8', errors='ignore').splitlines()
                combined_lines.append(f'# --- {rf.name} ---')
                combined_lines += rf_lines
            except Exception:
                pass
        combined = '\n'.join(combined_lines)
        pinned = [l for l in combined_lines if '==' in l and not l.strip().startswith('#')]
        unpinned_git = [l for l in combined_lines if l.strip().startswith('git+')]
        loose = [l for l in combined_lines if _re2.match(r'[\w.-]+\s*[><!]=', l.strip()) and '==' not in l]
        # packages with no version spec at all (bare package names)
        unpinned_bare = [l for l in combined_lines
                         if l.strip() and not l.strip().startswith('#')
                         and not l.strip().startswith('-')
                         and not l.strip().startswith('git+')
                         and '==' not in l and not _re2.match(r'[\w.-]+\s*[><!]=', l.strip())
                         and _re2.match(r'^[\w.-]+$', l.strip())]
        has_issues = unpinned_git or loose or unpinned_bare
        out = output_dir / 'requirements_DRAFT.txt'
        file_list = ', '.join(f.name for f in req_files_all)
        if pinned and not has_issues:
            header = [
                f'# Source: {file_list}',
                f'# {len(pinned)} packages — all pinned to exact versions.',
                '# Verify these versions match your environment before deposit.',
                '#',
            ]
            msg = '\n'.join(header) + '\n' + combined
            out.write_text(msg, encoding='utf-8-sig')
            return
        elif combined_lines:
            header = [f'# Source: {file_list}']
            if unpinned_git:
                header.append('# WARNING: git+ URLs present — pin to commit SHA before deposit')
            if loose:
                header.append('# WARNING: loose constraints (>=, !=) found — change to == before deposit')
            if unpinned_bare:
                header.append(f'# ACTION NEEDED: {len(unpinned_bare)} package(s) have no version — add ==X.Y.Z')
            header.append('#')
            # annotate unpinned lines inline
            annotated = []
            for l in combined_lines:
                s = l.strip()
                if s and not s.startswith('#') and not s.startswith('-') and '==' not in s:
                    annotated.append(l + '  # <-- pin version: packagename==X.Y.Z')
                else:
                    annotated.append(l)
            msg = '\n'.join(header) + '\n' + '\n'.join(annotated)
            out.write_text(msg, encoding='utf-8-sig')
            return
    # conda repo — handle environment.yml before generic dep file loop
    _env_file = min((f for f in all_files if f.name.lower() in {'environment.yml', 'environment.yaml'}),
                    key=lambda x: len(x.parts), default=None)
    if _env_file:
        try:
            import re as _renv
            _env_src = _env_file.read_text(encoding='utf-8', errors='ignore')
            _pkgs = []
            _in_deps = False
            for _line in _env_src.splitlines():
                _s = _line.strip()
                if _s.startswith('dependencies:'):
                    _in_deps = True
                    continue
                if _in_deps and _s and not _s.startswith('-') and not _s.startswith('#') and ':' in _s:
                    _in_deps = False
                if not _in_deps or not _s.startswith('-'):
                    continue
                _pkg = _s.lstrip('- ').strip()
                if _pkg and _pkg != 'pip' and not _pkg.startswith('pip:') and not _pkg.startswith('{'):
                    _pkgs.append(_pkg)
            _unpinned = [p for p in _pkgs if not _renv.match(r'^[\w\-\.]+=\d', p)]
            out = output_dir / 'requirements_DRAFT.txt'
            _lines = [
                f'# Source: {_env_file.name}',
                '# conda environment detected.',
                '# To capture exact pinned versions, run in your original environment:',
                '#   conda env export --no-builds > environment.yml',
                '#',
                '# Packages listed in environment.yml:',
                '',
            ]
            for _p in _pkgs:
                _lines.append(f'  {_p}')
            if _unpinned:
                _lines += [
                    '',
                    f'# WARNING: {len(_unpinned)} package(s) are unpinned or loosely pinned:',
                    f'#   {", ".join(_unpinned[:8])}',
                    '# Pin all packages with exact conda syntax: packagename=X.Y.Z',
                ]
            out.write_text('\n'.join(_lines), encoding='utf-8-sig')
            print('  -> requirements_DRAFT.txt (from environment.yml)')
            return
        except Exception:
            pass

    for dep_file in all_files:
        if dep_file.name.lower() in DEPENDENCY_FILES:
            try:
                existing = dep_file.read_text(encoding="utf-8", errors="ignore")
                pinned = [l for l in existing.splitlines() if "==" in l and not l.strip().startswith("#")]
                if pinned:
                    out = output_dir / "requirements_DRAFT.txt"
                    msg = ("# Existing file: " + dep_file.name + "\n"
                           "# " + str(len(pinned)) + " pinned packages found - no DRAFT needed.\n"
                           "# Verify versions are correct before deposit.\n#\n" + existing)
                    out.write_text(msg, encoding="utf-8-sig")
                    return
                else:
                    # existing file found but versions unpinned
                    if dep_file.name.lower() == "pyproject.toml":
                        # extract only dependencies from [project] section
                        import re as _re
                        dep_section = _re.search(
                            r'dependencies\s*=\s*\[([^\]]+)\]', existing, _re.DOTALL)
                        if dep_section:
                            raw_deps = dep_section.group(1)
                            pkgs = _re.findall(r'["\']([a-zA-Z][a-zA-Z0-9_\-\.]*)', raw_deps)
                            bounds = _re.findall(r'["\']([a-zA-Z][^"\']*)["\']\s*,?', raw_deps)
                            out = output_dir / "requirements_DRAFT.txt"
                            lines_out = [
                                "# pyproject.toml detected — dependencies extracted from [project] dependencies",
                                "# These have minimum version bounds but need exact pinning for reproducibility.",
                                "#", ""]
                            for b in bounds:
                                b = b.strip()
                                if b and not b.startswith("#"):
                                    lines_out.append(b + "  # pin to exact version")
                            out.write_text("\n".join(lines_out), encoding="utf-8-sig")
                            return
                    packages = [l.strip() for l in existing.splitlines()
                                if l.strip() and not l.strip().startswith("#")
                                and "=" in l and "[" not in l and "]" not in l]
                    if packages:
                        out = output_dir / "requirements_DRAFT.txt"
                        lines_out = ["# Existing " + dep_file.name + " found but versions are NOT pinned.",
                                     "# Add exact version numbers (e.g. pandas==2.1.3) before deposit.",
                                     "#", "# Current contents:", ""]
                        # Try to extract version bounds from embedded Pluto TOML
                        pluto_versions = {}
                        for jl_f in all_files:
                            if jl_f.suffix.lower() == '.jl':
                                jl_src = jl_f.read_text(encoding='utf-8', errors='ignore')
                                compat_m = re.search(r'\[compat\](.*?)(?:\[|$)', jl_src, re.DOTALL)
                                if compat_m:
                                    for vm in re.finditer(r'^(\w[\w\.]+)\s*=\s*"([^"]+)"', compat_m.group(1), re.MULTILINE):
                                        pluto_versions[vm.group(1).lower()] = vm.group(2)
                        def _pin_or_unknown(p):
                            if "==" in p or p.startswith("#"):
                                return p
                            pkg_name = p.split("==")[0].split(">=")[0].split("~=")[0].strip()
                            ver = pluto_versions.get(pkg_name.lower())
                            if ver:
                                return f"{pkg_name}>={ver.lstrip('~^')}  # from embedded Pluto compat block"
                            return p + "==UNKNOWN"
                        lines_out += [_pin_or_unknown(p) for p in packages]
                        out.write_text("\n".join(lines_out), encoding="utf-8-sig")
                        return
            except Exception:
                pass
    imports = set()

    import ast as _ast
    # scan .ipynb notebooks for imports
    import json as _json
    for f in all_files:
        if f.suffix.lower() == '.ipynb':
            try:
                nb = _json.loads(f.read_text(encoding='utf-8', errors='ignore'))
                for cell in nb.get('cells', []):
                    if cell.get('cell_type') == 'code':
                        src = ''.join(cell.get('source', []))
                        for line in src.splitlines():
                            line = line.strip()
                            m = re.match(r'^import\s+([\w]+)', line)
                            if m: imports.add(m.group(1))
                            m = re.match(r'^from\s+([\w]+)', line)
                            if m: imports.add(m.group(1))
            except Exception:
                pass
    for f in all_files:
        if f.suffix.lower() == '.py':
            try:
                src = f.read_text(encoding='utf-8', errors='ignore')
                try:
                    tree = _ast.parse(src)
                    for node in _ast.walk(tree):
                        if isinstance(node, _ast.Import):
                            for alias in node.names:
                                imports.add(alias.name.split('.')[0])
                        elif isinstance(node, _ast.ImportFrom):
                            if node.module:
                                imports.add(node.module.split('.')[0])
                except SyntaxError:
                    for line in src.splitlines():
                        line = line.strip()
                        m = re.match(r'^import\s+([\w]+)', line)
                        if m:
                            imports.add(m.group(1))
                        m = re.match(r'^from\s+([\w]+)', line)
                        if m:
                            imports.add(m.group(1))
            except Exception:
                pass

    # scan .jl / Pluto notebooks for 'using' statements
    julia_stdlib = {'Random', 'Statistics', 'LinearAlgebra', 'Dates', 'Printf',
                    'Base', 'Core', 'Main', 'Pkg', 'Test', 'Logging', 'REPL',
                    'InteractiveUtils', 'Distributed', 'Serialization',
                    'Markdown', 'Unicode', 'DelimitedFiles', 'SparseArrays',
                    'SharedArrays', 'Mmap', 'Profile', 'FileWatching'}
    julia_imports = set()
    for f in all_files:
        if f.suffix.lower() in {'.jl'}:
            try:
                src = f.read_text(encoding='utf-8', errors='ignore')
                for line in src.splitlines():
                    line = line.strip()
                    m = re.match(r'^using\s+([\w,\s]+)', line)
                    if m:
                        for pkg in re.split(r'[,\s]+', m.group(1)):
                            pkg = pkg.strip()
                            if pkg and pkg not in julia_stdlib:
                                julia_imports.add(pkg)
            except Exception:
                pass
    # Julia imports added after Python stdlib filter (see below)
    # filter out stdlib and local modules
    stdlib = {
        'os', 'sys', 're', 'math', 'json', 'csv', 'io',
        'time', 'datetime', 'pathlib', 'shutil', 'tempfile',
        'collections', 'itertools', 'functools', 'operator',
        'string', 'random', 'copy', 'abc', 'typing',
        'dataclasses', 'enum', 'warnings', 'logging',
        'unittest', 'subprocess', 'threading', 'multiprocessing',
        'argparse', 'configparser', 'hashlib', 'base64',
        'urllib', 'http', 'email', 'html', 'xml', 'sqlite3',
        'pickle', 'struct', 'array', 'queue', 'socket',
        'ssl', 'uuid', 'platform', 'inspect', 'importlib',
        'ast', 'dis', 'traceback', 'contextlib', 'weakref',
        'gc', 'ctypes', 'builtins', 'types', 'textwrap',
        'pprint', 'glob', 'fnmatch', 'stat', 'pwd', 'grp',
        'zipfile', 'tarfile', 'gzip', 'bz2', 'lzma',
        'zlib', 'binascii', 'codecs',
    }

    # local python files in repo
    local_modules = {
        f.stem.lower() for f in all_files
        if f.suffix.lower() == '.py'
    }

    external = sorted(
        imp for imp in imports
        if imp.lower() not in stdlib
        and imp.lower() not in local_modules
        and not imp.startswith('_')
    )
    # Merge Julia imports after Python stdlib filter so CSV etc. aren't excluded
    external = sorted(set(external) | {pkg for pkg in julia_imports if not pkg.startswith('_')})

    now = datetime.now().strftime('%Y-%m-%d %H:%M')

    lines = [
        '# ============================================================',
        '# DEPENDENCY EXTRACTION NOTICE',
        '# Generated by ValiChord Repository Readiness Check v15',
        '#',
        '# These package names were inferred from import statements',
        '# by static analysis. This list is NOT authoritative.',
        '#',
        '# - Local module names have been excluded',
        '# - Standard library modules have been excluded',
        '# - ALL VERSION NUMBERS ARE UNKNOWN',
        '#   You must supply exact versions before this file',
        '#   can be used for reproduction',
        '# - This list may include optional or unused packages',
        '# - This list may miss dynamically imported packages',
        '#',
        f'# Generated: {now}',
        '# ============================================================',
        '',
    ]

    # detect language-specific dependency systems
    all_suffixes = {f.suffix.lower() for f in all_files}
    if any(f.name == 'Snakefile' for f in all_files):
        all_suffixes.add('.smk')
    all_names = {f.name.lower() for f in all_files}

    # Extract version bounds from Project.toml [compat] or embedded Pluto TOML
    pluto_compat = {}
    # Standard Project.toml
    for toml_f in all_files:
        if toml_f.name.lower() == 'project.toml':
            try:
                toml_src = toml_f.read_text(encoding='utf-8', errors='ignore')
                compat_m = re.search(r'\[compat\](.*?)(?:\[|$)', toml_src, re.DOTALL)
                if compat_m:
                    for vm in re.finditer(r'^(\w[\w.]+)\s*=\s*"([^"]+)"', compat_m.group(1), re.MULTILINE):
                        pluto_compat[vm.group(1).lower()] = vm.group(2).lstrip('~^')
            except Exception:
                pass
    # Embedded Pluto TOML (overrides if present)
    for jl_f in all_files:
        if jl_f.suffix.lower() == '.jl':
            try:
                jl_src = jl_f.read_text(encoding='utf-8', errors='ignore')
                compat_m = re.search(r'\[compat\](.*?)(?:\[|$)', jl_src, re.DOTALL)
                if compat_m:
                    for vm in re.finditer(r'^(\w[\w.]+)\s*=\s*"([^"]+)"', compat_m.group(1), re.MULTILINE):
                        pluto_compat[vm.group(1).lower()] = vm.group(2).lstrip('~^')
            except Exception:
                pass
    if external:
        _is_julia_repo = '.jl' in all_suffixes and '.py' not in all_suffixes
        for pkg in external:
            ver = pluto_compat.get(pkg.lower())
            if ver:
                lines.append(f'{pkg}>={ver}  # from Project.toml or Pluto [compat] — not an exact pin')
            elif _is_julia_repo:
                lines.append(f'{pkg}  # Julia package — add to Project.toml instead of pinning here')
            else:
                lines.append(f'{pkg}==UNKNOWN')
    elif 'project.toml' in all_names and '.jl' in all_suffixes:
        lines += [
            '# Julia repository detected.',
            '# NOTE: Julia uses Project.toml + Manifest.toml for version pinning,',
            '# not requirements.txt. Packages below are for reference only.',
            '# Fix: julia --project=. -e "using Pkg; Pkg.add([...]); Pkg.resolve()" then commit Project.toml + Manifest.toml.',
            '# Dependencies are managed by Project.toml and Manifest.toml.',
            '# No requirements_DRAFT.txt needed.',
            '# To install: julia --project=. -e "using Pkg; Pkg.instantiate()"',
        ]
    elif 'renv.lock' in all_names or '.r' in all_suffixes:
        # If renv.lock present, extract exact versions
        if 'renv.lock' in all_names:
            renv_file = min((f for f in all_files if f.name.lower() == 'renv.lock'),
                            key=lambda x: len(x.parts), default=None)
            if renv_file:
                try:
                    import json as _rjson
                    renv_data = _rjson.loads(renv_file.read_text(encoding='utf-8', errors='ignore'))
                    pkgs = renv_data.get('Packages', {})
                    r_ver = renv_data.get('R', {}).get('Version', 'unknown')
                    lines += [f'# renv.lock present — R {r_ver}',
                              '# Exact versions locked. Run: Rscript -e "renv::restore()"',
                              '# Packages in renv.lock:', '']
                    for pname, pinfo in sorted(pkgs.items()):
                        ver = pinfo.get('Version', 'unknown')
                        src = pinfo.get('Source', 'CRAN')
                        lines.append(f'{pname}  # {ver}  ({src})')
                    out = output_dir / 'requirements_DRAFT.txt'
                    out.write_text('\n'.join(lines), encoding='utf-8-sig')
                    print('  -> requirements_DRAFT.txt (from renv.lock)')
                    return
                except Exception:
                    pass
        r_files = [f for f in all_files if f.suffix.lower() in {'.r', '.rmd', '.qmd'}]
        r_libs = set()
        lib_pat = re.compile(r'(?:library|require)\s*\(\s*["\']?([\w\.]+)["\']?\s*\)')
        vec_pkg_pat = re.compile(r'(?i)(?:packages?|pkgs?)\s*<-\s*c\s*\(([^)]+)\)')
        for rf in r_files:
            src = rf.read_text(encoding='utf-8', errors='ignore')
            for m in lib_pat.finditer(src):
                r_libs.add(m.group(1))
            for m in vec_pkg_pat.finditer(src):
                for pkg in re.findall(r'["\']+([\w\.]+)["\']', m.group(1)):
                    r_libs.add(pkg)
        # Build github_pkgs map and collect BiocManager/install.packages from install*.R
        _ghpat = re.compile(r'(?:devtools|remotes)::install_github\s*\(\s*["\']([^"\'/]+/([\w.-]+))["\']', re.IGNORECASE)
        _biocpat = re.compile(r'BiocManager::install\s*\(\s*c\s*\(([^)]+)\)', re.IGNORECASE)
        _ipat = re.compile(r'install\.packages\s*\(\s*c\s*\(([^)]+)\)', re.IGNORECASE)
        gh_map = {}
        extra_pkgs = set()
        for _rf in all_files:
            if re.match(r'(install|setup).*\.r$', _rf.name.lower()):
                try:
                    _rsrc = _rf.read_text(encoding='utf-8', errors='ignore')
                    for _m in _ghpat.finditer(_rsrc):
                        gh_map[_m.group(2).lower()] = _m.group(1)
                    for _bm in _biocpat.finditer(_rsrc):
                        for _pkg in re.findall(r'["\']([\w.]+)["\']', _bm.group(1)):
                            extra_pkgs.add(_pkg)
                    for _im in _ipat.finditer(_rsrc):
                        for _pkg in re.findall(r'["\']([\w.]+)["\']', _im.group(1)):
                            extra_pkgs.add(_pkg)
                except Exception:
                    pass
        r_libs = r_libs | extra_pkgs
        if r_libs:
            cran_list = [p for p in sorted(r_libs) if p.lower() not in gh_map]
            gh_list = [p for p in sorted(r_libs) if p.lower() in gh_map]
            lines += ['# R repository detected.',
                      '# Packages detected from library()/require() calls:',
                      '# Add version numbers before deposit.', '']
            if cran_list:
                lines.append('# CRAN packages:')
                lines += [f'{pkg}  # version unknown' for pkg in cran_list]
            if gh_list:
                if cran_list:
                    lines.append('')
                lines.append('# GitHub packages (no CRAN release -- pinning required):')
                for pkg in gh_list:
                    repo = gh_map.get(pkg.lower(), 'unknown/unknown')
                    lines.append(f'{pkg}  # GitHub: {repo} -- commit unknown')
        else:
            lines += [
                '# R repository detected.',
                '# If using renv: run renv::restore() to install dependencies.',
                '# If not using renv: add your R package dependencies manually.',
            ]
    elif '.do' in all_suffixes or '.ado' in all_suffixes:
        lines += [
            '# Stata repository detected.',
            '# List required Stata packages (ssc install) manually.',
        ]
    elif '.m' in all_suffixes:
        # Scan .m files for inline toolbox requirements
        toolbox_pattern = re.compile(r'[(%]?requires?\s+([\w\s]+(?:Toolbox|EEGLAB))', re.IGNORECASE)
        found_toolboxes = set()
        # Also scan README for toolbox requirements
        for rf in all_files:
            if rf.name.lower() in {'readme.md', 'readme.txt', 'readme.rst'}:
                try:
                    rsrc = rf.read_text(encoding='utf-8', errors='ignore')
                    for m in re.finditer(r'([\w\s]+Toolbox)', rsrc, re.IGNORECASE):
                        tb = m.group(1).strip()
                        if len(tb) < 60:
                            found_toolboxes.add(tb)
                except Exception:
                    pass
        eeglab_fns = {'pop_epoch', 'pop_autorej', 'pop_resample', 'pop_eegfiltnew',
                      'eeglab', 'pop_loadset', 'pop_saveset', 'runica'}
        found_eeglab = False
        for mf in all_files:
            if mf.suffix.lower() == '.m':
                try:
                    msrc = mf.read_text(encoding='utf-8', errors='ignore')
                    for m in toolbox_pattern.finditer(msrc):
                        tb = m.group(1).strip()
                    # Normalise abbreviated MathWorks names to full current names
                    if tb.lower() in {'statistics toolbox', 'statistics and machine learning toolbox'}:
                        tb = 'Statistics and Machine Learning Toolbox'
                    found_toolboxes.add(tb)
                    if any(fn in msrc for fn in eeglab_fns):
                        found_eeglab = True
                except Exception:
                    pass
        if found_eeglab:
            found_toolboxes.add('EEGLAB (third-party — download from sccn.ucsd.edu/eeglab)')
        if found_toolboxes:
            lines += ['# MATLAB repository detected.',
                      '# Required toolboxes detected from code comments:']
            for tb in sorted(found_toolboxes):
                lines.append(f'# - {tb}')
            lines += ['# Verify these are licensed and installed before running.', '']
        else:
            lines += [
                '# MATLAB repository detected.',
                '# List required MATLAB toolboxes manually.',
        ]
    else:
        lines += [
            '# No external imports detected.',
            '# Add your dependencies manually.',
        ]

    lines += [
        '',
        '# ============================================================',
        '# Local modules found in this repository (excluded above):',
    ]
    for m in sorted(local_modules):
        lines.append(f'# {m}')
    lines.append('# ============================================================')

    out = output_dir / 'requirements_DRAFT.txt'
    out.write_text('\n'.join(lines), encoding='utf-8-sig')
    print(f"  → requirements_DRAFT.txt "
          f"({len(external)} packages detected)")


# ── QUICKSTART_DRAFT.md ──────────────────────────────────────────────────────


def _renumber_steps(steps):
    """Resequence numbered steps (lines starting with a digit and .) after deletions."""
    result = []
    n = 1
    for s in steps:
        import re as _re
        if _re.match(r'^\d+\.', s):
            s = _re.sub(r'^\d+\.', f'{n}.', s, count=1)
            n += 1
        elif s.startswith('N.'):
            s = s.replace('N.', f'{n}.', 1)
            n += 1
        result.append(s)
    return result


def _quickstart_step2(all_files, code_files):
    """Return language-appropriate step 2 for QUICKSTART."""
    suffixes = {f.suffix.lower() for f in code_files}
    if any(f.name == 'Snakefile' for f in all_files):
        suffixes.add('.smk')
    names = {f.name.lower() for f in all_files}
    # Docker repo — replace all install steps with build/run
    if 'dockerfile' in names:
        import re as _redock
        _img = 'my-analysis'
        _df = min((f for f in all_files if f.name == 'Dockerfile'),
                  key=lambda x: len(x.parts), default=None)
        if _df:
            try:
                _dsrc = _df.read_text(encoding='utf-8', errors='ignore')
                # try to derive image name from repo dir or LABEL
                _label = _redock.search(r'LABEL.*image[_-]?name[=\s]+["\']?([\w_-]+)', _dsrc, _redock.IGNORECASE)
                if _label:
                    _img = _label.group(1).lower()
                else:
                    # use parent directory name as image name
                    _img = _df.parent.name.lower().replace(' ', '-') or 'my-analysis'
            except Exception:
                pass
        return [
            '2. Build the Docker image: `docker build -t ' + _img + ' .`',
            '3. Run: `docker run -v $(pwd)/data:/app/data ' + _img + '`',
            '   (adjust volume mounts to match your data directory)',
        ]
    # conda repo takes priority — single env file replaces all other dep steps
    if 'environment.yml' in names or 'environment.yaml' in names:
        env_file = 'environment.yml' if 'environment.yml' in names else 'environment.yaml'
        env_name = 'myenv'
        env_path = min((f for f in all_files if f.name.lower() == env_file),
                       key=lambda x: len(x.parts), default=None)
        if env_path:
            import re as _re
            m = _re.search(r'^name:\s*(\S+)', env_path.read_text(encoding='utf-8', errors='ignore'), _re.MULTILINE)
            if m:
                env_name = m.group(1)
        return [f'2. Create and activate environment: `conda env create -f {env_file} && conda activate {env_name}`']
    if '.smk' in suffixes or any(f.name == 'Snakefile' for f in all_files):
        return ['2. Run the Snakemake workflow: `snakemake --cores all`',
                '   (add --use-conda if per-rule conda: directives are present)']
    if any(f.suffix.lower() == '.nf' for f in all_files):
        nf_main = next((f.name for f in all_files if f.name.lower() == 'main.nf'), 'main.nf')
        return ['2. Run the Nextflow pipeline:',
                f'   nextflow run {nf_main}',
                '   (add -with-docker or -with-conda if container/conda directives are present)']
    if '.r' in suffixes or '.rmd' in suffixes:
        # Check for reticulate — R calls Python at runtime, need both installs
        import re as _reretc
        _has_reticulate = any(
            _reretc.search(
                r'library\s*\(\s*reticulate|reticulate::',
                f.read_text(encoding='utf-8', errors='ignore')
            )
            for f in all_files if f.suffix.lower() in {'.r', '.rmd'}
        )
        _has_req = any(
            _reretc.match(r'requirements.*\.txt$', f.name.lower())
            for f in all_files
        )
        if _has_reticulate and _has_req:
            return [
                '2. Install Python dependencies: `pip install -r requirements.txt`',
                '3. Restore R environment: `Rscript -e "renv::restore()"`',
                '   (reticulate detected -- both R and Python environments required)',
            ]
        if 'renv.lock' in names:
            if _has_reticulate and _has_req:
                return ['2. Install Python dependencies: `pip install -r requirements.txt`',
                        '   Then restore R environment: `Rscript -e "renv::restore()"`',
                        '   (reticulate detected — both environments required)']
            return ['2. Restore R environment: `Rscript -e "renv::restore()"`',
                    '   (renv.lock present — exact package versions will be installed)']
        install_r = next((f.name for f in all_files
                         if re.match(r'install.*\.r$', f.name.lower())), None)
        if install_r:
            return ['2. Install R dependencies: `Rscript ' + install_r + '`']
        return ['2. Add version numbers to packages in `requirements_DRAFT.txt`, '
                'then run `renv::snapshot()` to create `renv.lock`']
    if '.jl' in suffixes:
        names = {f.name.lower() for f in all_files}
        if 'project.toml' in names:
            return ['2. Dependencies managed by `Project.toml` — run '
                    '`julia --project=. -e "using Pkg; Pkg.instantiate()"`']
        else:
            # No Project.toml — check for runtime Pkg.add() anti-pattern
            import re as _rejl
            _has_pkg_add = any(
                _rejl.search(r'Pkg\.add\s*\(', f.read_text(encoding='utf-8', errors='ignore'))
                for f in all_files if f.suffix.lower() == '.jl'
            )
            if _has_pkg_add:
                return ['2. Create Project.toml and Manifest.toml to lock package versions:',
                        '   julia --project=. -e "using Pkg; Pkg.add([\"Optim\", ...]); Pkg.resolve()"',
                        '   Then commit both Project.toml and Manifest.toml',
                        '   (see [CQ] finding — runtime Pkg.add() does not pin versions)']
            # No Project.toml — manually install detected packages
            jl_pkgs = sorted({
                pkg for f in all_files if f.suffix.lower() == '.jl'
                for line in f.read_text(encoding='utf-8', errors='ignore').splitlines()
                for m in [__import__('re').match(r'^using\s+([\w,\s]+)', line.strip())]
                if m
                for pkg in __import__('re').split(r'[,\s]+', m.group(1))
                if pkg.strip() and pkg.strip() not in {
                    'Random','Statistics','LinearAlgebra','Dates','Printf',
                    'Base','Core','Main','Pkg','Test','Logging','REPL',
                    'InteractiveUtils','Distributed','Serialization',
                    'Markdown','Unicode','DelimitedFiles','SparseArrays'}
            })
            if jl_pkgs:
                pkg_list = ', '.join(f'"{p}"' for p in jl_pkgs)
                return [f'2. Install required packages: `julia -e \'using Pkg; Pkg.add([{pkg_list}])\'`']
            return ['2. Install required Julia packages manually using `julia -e "using Pkg; Pkg.add(\"PackageName\")"`']
    # check for pyproject.toml package
    names = {f.name.lower() for f in all_files}
    if 'pyproject.toml' in names:
        return ['2. Install as editable package: `pip install -e .`']
    # Python — check if already pinned
    has_pinned = any(
        f.name.lower() in DEPENDENCY_FILES and
        any('==' in l for l in f.read_text(encoding='utf-8', errors='ignore').splitlines()
            if not l.strip().startswith('#'))
        for f in all_files if f.name.lower() in DEPENDENCY_FILES
    )
    has_requirements = any(f.name.lower() == 'requirements.txt' for f in all_files)
    if has_pinned:
        # Check if any requirements*.txt has git+ URLs or loose constraints
        import re as _reqs
        req_files_qs = [f for f in all_files if _reqs.match(r'requirements.*\.txt$', f.name.lower())]
        has_git_urls = any(
            any(l.strip().startswith('git+') for l in f.read_text(encoding='utf-8', errors='ignore').splitlines())
            for f in req_files_qs
        )
        extra_reqs = [f.name for f in req_files_qs if f.name.lower() != 'requirements.txt']
        if has_git_urls:
            cmds = ['pip install -r requirements.txt'] + [f'pip install -r {n}' for n in extra_reqs]
            cmd_lines = ['   ```bash'] + [f'   {c}' for c in cmds] + ['   ```']
            return ['2. Install dependencies (WARNING: git+ URLs in requirements_extra.txt need pinning before deposit):'] + cmd_lines
        elif extra_reqs:
            cmds = ['pip install -r requirements.txt'] + [f'pip install -r {n}' for n in extra_reqs]
            cmd_lines = ['   ```bash'] + [f'   {c}' for c in cmds] + ['   ```']
            return ['2. Install all dependencies:'] + cmd_lines
        # Check for known TF/numpy style conflicts in requirements
        import re as _recn
        _pinned = {}
        for _rf in all_files:
            if _recn.match(r'requirements.*\.txt$', _rf.name.lower()):
                try:
                    for _line in _rf.read_text(encoding='utf-8', errors='ignore').splitlines():
                        _m = _recn.match(r'^([\w.-]+)==([\d.]+)', _line.strip())
                        if _m: _pinned[_m.group(1).lower()] = _m.group(2)
                except Exception: pass
        def _ver(v, n=2): return tuple(int(x) for x in v.split('.')[:n])
        _has_conflict = (
            ('tensorflow' in _pinned and 'numpy' in _pinned and
             _ver(_pinned['tensorflow']) < (2,13) and _ver(_pinned['numpy']) >= (1,24))
            or ('torch' in _pinned and 'numpy' in _pinned and
                _ver(_pinned['torch']) < (2,0) and _ver(_pinned['numpy'],1) >= (2,))
        )
        if _has_conflict:
            return ['2. WARNING: version conflicts in requirements.txt — see [CN] finding.',
                    '   Fix conflicts before running: `pip install -r requirements.txt` will fail.']
        # Check for Python 2 syntax — pinned versions irrelevant if code won't run
        _has_py2 = any(
            re.search(r'^[ \t]*print\s+["\' \w]', f.read_text(encoding='utf-8', errors='ignore'), re.MULTILINE)
            for f in all_files if f.suffix.lower() == '.py'
        )
        if _has_py2:
            return ['2. WARNING: Python 2 syntax detected — see [CP] finding.',
                    '   Fix Python 2 syntax before installing: code will not run in Python 3.']
        _model_indicators = {'model', 'clf', 'classifier', 'regressor', 'estimator', 'pipeline', 'weights'}
        _has_model_pkl = any(
            f.suffix.lower() in {'.pkl', '.pickle'} and (
                any(ind in f.name.lower() for ind in _model_indicators) or
                any(part.lower() in {'models', 'model', 'checkpoints'} for part in f.parts)
            )
            for f in (all_files or [])
        )
        if _has_model_pkl:
            return ['2. Install dependencies: `pip install -r requirements.txt`',
                    '   NOTE: A committed model binary (.pkl) is present — see [CS] finding.',
                    '   Pickle files are version-specific; ensure your Python/library versions',
                    '   match those used to train the model, or retrain from scratch.']
        return ['2. Install dependencies: `pip install -r requirements.txt`']
    if '.m' in suffixes:
        import re as _rem2
        _tbs = []
        for _f in (all_files or []):
            if _f.name.lower() in {'readme.md', 'readme.txt', 'readme.rst'}:
                try:
                    for _tm in _rem2.finditer(r'([\w\s]+Toolbox)', _f.read_text(encoding='utf-8', errors='ignore'), _rem2.IGNORECASE):
                        _tb = _tm.group(1).strip()
                        if len(_tb) < 60: _tbs.append(_tb)
                except Exception: pass
        _tb_note = ('Toolboxes required: ' + ', '.join(sorted(set(_tbs)))) if _tbs else 'Check README for required toolboxes'
        return ['2. Ensure required MATLAB toolboxes are licensed and installed.',
                f'   {_tb_note}']
    if '.do' in suffixes or '.ado' in suffixes:
        return ['2. Open Stata and ensure required packages are installed']
    if has_requirements:
        return ['2. Pin the version numbers in your existing `requirements.txt` (e.g. pandas==2.1.3)']
    return ['2. Add version numbers to `requirements_DRAFT.txt` and rename to `requirements.txt`']

def _install_instructions(code_files, all_files=None):
    """Return language-appropriate install instructions."""
    suffixes = {f.suffix.lower() for f in code_files}
    # Docker repo — no separate install step needed
    if all_files and any(f.name == 'Dockerfile' for f in all_files):
        return []
    lines = []
    # conda repo — step 2 already covers install via _quickstart_step2; suppress step 3
    if all_files:
        names = {f.name.lower() for f in all_files}
        if 'environment.yml' in names or 'environment.yaml' in names:
            return []
    # Snakemake repo — step 2 is `snakemake --cores all`; suppress all further steps
    if all_files and any(f.name == 'Snakefile' or f.suffix.lower() == '.smk' for f in all_files):
        return []
    # Snakemake repo — step 2 is `snakemake --cores all`; suppress all further steps
    if all_files and any(f.name == 'Snakefile' or f.suffix.lower() == '.smk' for f in all_files):
        return []
    # Julia: step 2 already covers install via _quickstart_step2; suppress step 3
    if '.jl' in suffixes:
        return []  # handled in step 2
    if '.r' in suffixes or '.rmd' in suffixes:
        _all = all_files or []
        _names = {f.name.lower() for f in _all}
        if 'renv.lock' in _names:
            return lines  # step 2 already has renv::restore
        import re as _re3r
        if any(_re3r.match(r'install.*\.r$', fn) for fn in _names):
            return lines  # step 2 already has Rscript install_deps.R
        # No renv.lock — renv::restore() would fail; suggest install.packages instead
        _r_pkgs = []
        import re as _re3r2
        for _f in (all_files or []):
            if _re3r2.match(r'requirements.*\.txt$', _f.name.lower()):
                try:
                    for _line in _f.read_text(encoding='utf-8', errors='ignore').splitlines():
                        _pkg = _re3r2.split(r'[>=<!\[; ]', _line.strip())[0].strip()
                        if _pkg and not _pkg.startswith('#'): _r_pkgs.append(_pkg)
                except Exception: pass
        if _r_pkgs:
            _pkg_str = ', '.join(f"'{p}'" for p in _r_pkgs[:6])
            lines.append('3. Install R dependencies: '
                         f'`Rscript -e "install.packages(c({_pkg_str}))"` '
                         '(no renv.lock — see [AO] finding to create one)')
        else:
            lines.append('3. Install R dependencies (no renv.lock present — '
                         'see [AO] finding): `Rscript -e "renv::init(); renv::snapshot()"`')
    if '.do' in suffixes or '.ado' in suffixes:
        lines.append('3. Open Stata and run the master do-file listed above')
    if '.m' in suffixes:
        return lines  # MATLAB: step 2 covers toolbox check; step 3 not needed
    if '.py' in suffixes or (not lines and '.r' not in suffixes and '.rmd' not in suffixes
                              and '.nf' not in suffixes):
        # Only add step 3 pip install if step 2 didn't already cover it
        import re as _re3
        req_files_check = [f for f in all_files if _re3.match(r'requirements.*\.txt$', f.name.lower())]
        if not req_files_check:
            lines.append('3. Install dependencies: `pip install -r requirements.txt`')
    return lines

def _generate_quickstart_draft(repo_dir, all_files,
                                 findings, output_dir):
    """Generate QUICKSTART_DRAFT.md with inferred execution order."""

    now = datetime.now().strftime('%Y-%m-%d %H:%M')

    archive_dirs = {"old", "archive", "deprecated", "unused", "backup", "old_versions"}
    _stata_lib_dirs = {'plus', 'personal', 'stbplus'}
    code_files = [
        f for f in all_files
        if (f.suffix.lower() in CODE_EXTENSIONS or f.name == 'Snakefile')
        and f.name not in {"__init__.py", "__main__.py"}
        and not any(p.name.lower() in archive_dirs for p in f.parents)
        and not ('ado' in f.parts and any(p in _stata_lib_dirs for p in f.parts))
    ]

    # try to find execution order from README run block
    readme_order = []
    for rf in all_files:
        if rf.name.lower() in {'readme.md', 'readme.txt', 'readme.rst'}:
            try:
                rsrc = rf.read_text(encoding='utf-8', errors='ignore')
                # Find python/Rscript commands in code blocks
                for m in re.finditer(
                    r'(?:python|Rscript|julia)\s+([\w/.-]+\.(?:py|r|jl|m|sh))\b',
                    rsrc, re.IGNORECASE):
                    fname = m.group(1).split('/')[-1]
                    match = next((f for f in code_files if f.name == fname), None)
                    if match and match not in readme_order:
                        readme_order.append(match)
            except Exception:
                pass
    # try to find numbered scripts — support integer (01_, 1_), decimal (1.2_),
    # period/period-space (1. name, 1.name), and compound (3-1. name) prefixes;
    # sort by (major, minor) tuple for correct order
    numbered = []
    for f in code_files:
        # Separator: underscore, hyphen, or period-not-followed-by-digit
        m = re.match(r'^(\d+)(?:[.\-](\d+))?(?:[_\-]|\.(?!\d))', f.name)
        if m:
            major = int(m.group(1))
            minor = int(m.group(2)) if m.group(2) else 0
            numbered.append(((major, minor), f))
    numbered.sort(key=lambda x: x[0])

    # _PartN infix pattern (e.g. Master_Part1_Data.m, Script_Part2.R)
    # Only used when leading-prefix detection found nothing
    if not numbered:
        _part_candidates = []
        for f in code_files:
            mp = re.search(r'[_\-][Pp]art(\d+)', f.stem)
            if mp:
                _part_candidates.append(((int(mp.group(1)), 0), f))
        # Require ≥2 distinct part numbers to treat as an ordered sequence
        if len({key[0] for key, _ in _part_candidates}) >= 2:
            numbered = sorted(_part_candidates, key=lambda x: x[0])

    # prefer README order over alphabetical — track source for confidence level
    _numbered_from_filenames = bool(numbered)
    if readme_order and not numbered:
        numbered = [((i + 1, 0), f) for i, f in enumerate(readme_order)]

    # Master run-script — if a run_all / run.sh exists at any depth, use it as
    # the single entry point rather than listing every numbered file individually
    import re as _rerun
    _MAIN_ENTRY_NAMES = {'main.m', 'main.py', 'main.ipynb', 'index.ipynb'}
    _run_candidates = [
        f for f in all_files
        if _rerun.match(r'^run[_\-]?all\b.*\.(sh|bash|py|do)$', f.name.lower())
        or f.name.lower() in {'run.sh', 'run.bash', 'master.sh', 'master.do',
                               'run_analysis.sh', 'run_replication.sh'}
        or f.name.lower() in _MAIN_ENTRY_NAMES
    ]
    # pick shallowest (root-level wins over subfolder), same logic as README picker
    _run_script = min(
        _run_candidates,
        key=lambda x: len(x.relative_to(repo_dir).parts),
        default=None
    )
    def _entry_cmd(f):
        """Return the shell command to run a single entry-point file."""
        rel = f.relative_to(repo_dir)
        ext = f.suffix.lower()
        if ext in {'.sh', '.bash'}:
            return str(rel), f'bash {rel}'
        elif ext == '.py':
            return str(rel), f'python {rel}'
        elif ext == '.do':
            return str(rel), f'stata -b do {rel}'
        elif ext == '.m':
            return str(rel), f'matlab -batch "run(\'{rel}\')"'
        elif ext == '.ipynb':
            return str(rel), f'jupyter nbconvert --to notebook --execute {rel}'
        else:
            return str(rel), f'./{rel}'

    if _run_script and len(code_files) > 3:
        _run_rel_str, _run_cmd = _entry_cmd(_run_script)

        # Any other main.* files that weren't chosen as the primary entry point
        _secondary_mains = [
            f for f in _run_candidates
            if f != _run_script and f.name.lower() in _MAIN_ENTRY_NAMES
        ]
        _secondary_block = []
        for _sf in _secondary_mains:
            _sf_rel_str, _sf_cmd = _entry_cmd(_sf)
            _secondary_block += [
                '',
                f'### Also: `{_sf_rel_str}`',
                '',
                '> ⚠️ A second entry point was detected alongside the primary script.',
                '> It may cover a separate part of the analysis — run it independently if needed.',
                '',
                '```bash',
                _sf_cmd,
                '```',
            ]

        _run_lines = [
            '# ValiChord Repository Readiness Check — Quick Start',
            '',
            '> ✅ **Master run script detected.**',
            '> **Confidence level: HIGH** — a single orchestrating script was found.',
            '> Run the script below to execute the full pipeline.',
            '',
            '---',
            '',
            '## Execution',
            '',
            f'```bash',
            _run_cmd,
            '```',
            '',
            f'(`{_run_rel_str}` orchestrates the full analysis pipeline.)',
            *_secondary_block,
            '',
            '---',
            '',
            '## Before Running',
            '',
            *_renumber_steps([
                *([] if any(
                    f.name.lower() in README_NAMES and
                    len(f.read_text(encoding='utf-8', errors='ignore').strip()) > 500
                    for f in all_files
                ) else ['1. Complete `README_DRAFT.md` and rename to `README.md`']),
                *(_quickstart_step2(all_files, code_files)),
                *_install_instructions(code_files, all_files),
                'N. Test on a **clean machine** before publishing',
            ]),
            '',
            '---',
            '',
            f'*Generated by ValiChord Repository Readiness Check v15 — {now}*',
        ]
        out = output_dir / 'QUICKSTART_DRAFT.md'
        out.write_text('\n'.join(_run_lines), encoding='utf-8-sig')
        print(f"  → QUICKSTART_DRAFT.md (run_all entry point)")
        return

    # Shiny app — generate dedicated interactive-app QUICKSTART
    import re as _reshiny
    _shiny_names = {'server.r', 'ui.r', 'app.r'}
    _all_names_lower = {f.name.lower() for f in all_files}
    # Monorepo — detect independent sub-projects and generate per-project sections
    import re as _remono
    _dep_files_mono = {'requirements.txt', 'environment.yml', 'renv.lock',
                       'pyproject.toml', 'pipfile', 'setup.py'}
    _subdirs_mono = {}
    for _f in all_files:
        try:
            _rel = _f.relative_to(repo_dir)
            if len(_rel.parts) >= 2:
                _subdirs_mono.setdefault(_rel.parts[0], []).append(_f)
        except Exception:
            pass
    # Peel single common top-level wrapper (e.g. zip extracts as monorepo/paper1/...)
    if len(_subdirs_mono) == 1:
        _wrapper_files = list(_subdirs_mono.values())[0]
        _subdirs_mono = {}
        for _f in _wrapper_files:
            try:
                _rel = _f.relative_to(repo_dir)
                if len(_rel.parts) >= 3:
                    _subdirs_mono.setdefault(_rel.parts[1], []).append(_f)
            except Exception:
                pass
    _subprojects_mono = []
    for _sd, _sfiles in _subdirs_mono.items():
        _sfnames = {_f.name.lower() for _f in _sfiles}
        _ssuffixes = {_f.suffix.lower() for _f in _sfiles}
        if (_ssuffixes & {'.py', '.r', '.rmd', '.jl', '.m', '.do'}) and \
           (_sfnames & _dep_files_mono or _sfnames & {'readme.md', 'readme.txt'}):
            _subprojects_mono.append((_sd, _sfiles, _ssuffixes, _sfnames))
    _is_monorepo = len(_subprojects_mono) >= 2
    if _is_monorepo:
        mono_lines = [
            '# ValiChord Repository Readiness Check — Quick Start',
            '',
            '> ⚠️ **MONOREPO DETECTED** — This repository contains multiple independent',
            '> sub-projects. Run each sub-project independently — they are NOT sequential.',
            '',
            '---',
            '',
        ]
        for _sd, _sfiles, _ssuffixes, _sfnames in _subprojects_mono:
            _has_renv = 'renv.lock' in _sfnames
            _has_req = 'requirements.txt' in _sfnames
            _has_env = 'environment.yml' in _sfnames or 'environment.yaml' in _sfnames
            _is_r = bool(_ssuffixes & {'.r', '.rmd'})
            _is_py = '.py' in _ssuffixes
            # Find entry point
            _has_index_html = any(_f.name.lower() == 'index.html' for _f in _sfiles)
            _has_js = any(_f.suffix.lower() == '.js' for _f in _sfiles)
            _has_analysis_code = any(
                _f.suffix.lower() in {'.py', '.r', '.rmd', '.jl', '.m', '.do'}
                for _f in _sfiles
            )
            _entry = next(
                (_f.name for _f in _sfiles
                 if _f.suffix.lower() in {'.py', '.r', '.rmd', '.jl', '.m', '.do'}
                 and _remono.match(r'^(main|run|analyse|analyze|model|pipeline|app)',
                                   _f.name.lower())),
                next((_f.name for _f in _sfiles
                      if _f.suffix.lower() in {'.py', '.r', '.rmd', '.jl', '.m', '.do'}),
                     None)
            )
            if _has_index_html and _has_js and not _has_analysis_code:
                _entry = 'index.html'
                _lang = 'web'
            _lang = 'Python' if _is_py else ('R' if _is_r else 'unknown')
            mono_lines += [
                f'## Sub-project: {_sd}/ ({_lang})',
                '',
                f'1. `cd {_sd}/`',
            ]
            step = 2
            if _has_env:
                mono_lines.append(f'{step}. `conda env create -f environment.yml && conda activate ...`')
                step += 1
            elif _has_renv:
                mono_lines.append(f'{step}. `Rscript -e "renv::restore()"`')
                step += 1
            elif _has_req:
                mono_lines.append(f'{step}. `pip install -r requirements.txt`')
                step += 1
            if _entry:
                if _is_py:
                    mono_lines.append(f'{step}. `python {_entry}`')
                elif _is_r:
                    mono_lines.append(f'{step}. `Rscript {_entry}`')
                else:
                    mono_lines.append(f'{step}. Run `{_entry}`')
            mono_lines.append('')
        mono_content = '\n'.join(mono_lines) + '\n'
        output_file = output_dir / 'QUICKSTART_DRAFT.md'
        output_file.write_text(mono_content, encoding='utf-8')
        return output_file

    _is_shiny_repo = (
        any(n in _all_names_lower for n in _shiny_names) or
        any(
            f.suffix.lower() in {'.r', '.rmd'} and
            _reshiny.search(
                r'library\s*\(\s*shiny\s*\)|shiny::runApp|shinyApp\s*\(',
                f.read_text(encoding='utf-8', errors='ignore')
            )
            for f in all_files
        )
    )
    if _is_shiny_repo:
        _all_names = {f.name.lower() for f in all_files}
        _has_renv = 'renv.lock' in _all_names
        _app_parents = [
            f.parent for f in all_files
            if f.name.lower() in {'server.r', 'ui.r'}
            and f.parent != repo_dir
        ]
        _app_dir = (
            "'" + str(_app_parents[0].relative_to(repo_dir)).replace('\\', '/') + "'"
            if _app_parents else '.'
        )
        shiny_lines = [
            '# ValiChord Repository Readiness Check — Quick Start',
            '',
            '> ⚠️ **This repository contains a Shiny web application.**',
            '> **Do NOT run `server.R` or `ui.R` directly.**',
            '> Reproduction requires launching the app and interacting with the UI.',
            '',
            '---',
            '',
            '## Launching the Shiny App',
            '',
        ]
        step = 1
        _readme_exists = any(
            f.name.lower() in {'readme.md', 'readme.txt'} and
            len(f.read_text(encoding='utf-8', errors='ignore').strip()) > 500
            for f in all_files
        )
        if not _readme_exists:
            shiny_lines.append(f'{step}. Complete `README_DRAFT.md` and rename to `README.md`')
            step += 1
        if _has_renv:
            shiny_lines.append(f'{step}. Restore R environment: `Rscript -e "renv::restore()"`')
            step += 1
        else:
            shiny_lines.append(f'{step}. Install R dependencies: `Rscript -e "install.packages(c(\'shiny\', ...))"` (see README_DRAFT)')
            step += 1
        shiny_lines += [
            f'{step}. Launch the app: `Rscript -e "shiny::runApp(' + _app_dir + ')"` ',
            f'{step+1}. Open browser at `http://127.0.0.1:PORT` (port shown in console output)',
            f'{step+2}. See **[DB] finding** for required interaction instructions and expected outputs',
            '',
            '---',
            '',
            '> ⚠️ **IMPORTANT**: No output files are generated automatically.',
            '> Reproduction requires manual interaction with the UI and visual verification',
            '> of charts and tables against published figures.',
        ]
        shiny_content = '\n'.join(shiny_lines) + '\n'
        output_file = output_dir / 'QUICKSTART_DRAFT.md'
        output_file.write_text(shiny_content, encoding='utf-8')
        return output_file

    lines = [
        '# ValiChord Repository Readiness Check — Quick Start',
        '',
        *(['> ✅ **Execution order inferred from numbered script filenames.**',
           '> **Confidence level: HIGH** — numeric prefixes make order explicit.',
           '> Verify this matches your intended pipeline before publishing.']
          if _numbered_from_filenames else
          ['> ⚠️ **IMPORTANT — THIS EXECUTION ORDER IS INFERRED**',
           '> **AND HAS NOT BEEN VALIDATED.**',
           '> ',
           '> The script order below was generated by automated',
           '> analysis and may be incorrect. Do not rely on it',
           '> without manual verification against your own',
           '> knowledge of the pipeline.',
           '> ',
           '> **Confidence level: LOW**']),
        '',
        '---',
        '',
    ]

    if numbered:
        lines += [
            '## Inferred Execution Order',
            '(from numbered script filenames)' if _numbered_from_filenames else '(from README run commands)',
            '',
        ]
        for i, (_, f) in enumerate(numbered, 1):
            rel = f.relative_to(repo_dir)
            lines.append(f'{i}. `{rel}`')
        lines.append('')
    else:
        lines += [
            '## Script Files Found',
            '',
            'No numbered scripts detected. '
            'The following scripts were found — ',
            'you must specify the correct execution order:',
            '',
        ]
        notebook_extensions = NOTEBOOK_EXTENSIONS

        # Detect JS/web-only repos and show entry point instead of listing all JS files
        _qs_web_suffixes = {'.js', '.html', '.css', '.ts'}
        _qs_analysis_suffixes = {'.py', '.r', '.rmd', '.jl', '.do', '.m'}
        _qs_code_suffixes = {f.suffix.lower() for f in code_files}
        _qs_is_web = (
            bool(_qs_code_suffixes & _qs_web_suffixes) and
            not bool(_qs_code_suffixes & _qs_analysis_suffixes)
        )
        _qs_index = next(
            (f for f in all_files if f.name.lower() == 'index.html'
             and len(f.relative_to(repo_dir).parts) == 1),
            next((f for f in all_files if f.name.lower() == 'index.html'), None)
        )
        if _qs_is_web and _qs_index:
            lines += [
                '> ℹ️ **This is a web application.**',
                '> JavaScript files are loaded by the browser — they are not executed sequentially.',
                '',
                '## Entry Point',
                '',
                f'Open `{_qs_index.relative_to(repo_dir)}` in a WebXR-capable browser.',
                '',
                '> If this is a VR/WebXR application, a compatible headset (e.g. Meta Quest)',
                '> or browser with WebXR support is required.',
                '',
            ]
            # Skip the rest of the file listing for web repos
            lines += [
                '---',
                '',
                '*Generated by ValiChord Repository Readiness Check v15*',
            ]
            output_file = output_dir / 'QUICKSTART_DRAFT.md'
            output_file.write_text('\n'.join(lines) + '\n', encoding='utf-8')
            return output_file

        for f in sorted(code_files, key=lambda x: x.name):
            if f.suffix.lower() in notebook_extensions:
                continue  # notebooks listed separately below
            rel = f.relative_to(repo_dir)
            lines.append(f'- `{rel}`')
        # also list notebooks
        notebook_files = [f for f in all_files if f.suffix.lower() in NOTEBOOK_EXTENSIONS]
        _has_j_finding = any(isinstance(f, dict) and f.get('mode') == 'J' for f in findings)
        for f in sorted(notebook_files, key=lambda x: x.name):
            rel = f.relative_to(repo_dir)
            if _has_j_finding:
                lines.append(f'- `{rel}` ⚠️ WARNING: non-linear execution order detected — '
                             f'see [J] finding. Do NOT run top-to-bottom until execution '
                             f'order is resolved and documented.')
            else:
                if f.suffix.lower() in {'.rmd', '.qmd'}:
                    lines.append(f'- `{rel}` (open in RStudio and knit, or run via: Rscript -e \'rmarkdown::render("{rel}")\')')
                else:
                    lines.append(f'- `{rel}` (open in Jupyter and run all cells top to bottom)')
        lines.append('')

    lines += [
        '---',
        '',
        '## Before Running',
        '',
        *_renumber_steps([
            *([] if any(
                f.name.lower() in README_NAMES and
                len(f.read_text(encoding='utf-8', errors='ignore').strip()) > 500 and
                sum(1 for s in ['usage', 'requirement', 'installation', 'data', 'reproduc', 'run']
                    if s in f.read_text(encoding='utf-8', errors='ignore').lower()) >= 3
                for f in all_files
            ) else ['1. Complete `README_DRAFT.md` and rename to `README.md`']),
            *(_quickstart_step2(all_files, code_files)),
            *_install_instructions(code_files, all_files),
            'N. Test on a **clean machine** — not just a new folder '
            'on your development machine',
            *(['WARNING: Internet access required at runtime -- '
               'code fetches live data. Document snapshot date and source version in README.']
              if any(isinstance(f, dict) and f.get('mode') in {'AS', 'CI', 'AQ'}
                     for f in findings)
              else []),
            *(['WARNING: GPU required — code uses torch.device("cuda") with no CPU fallback. '
               'A CUDA-capable GPU is required to run this code. '
               'See [CV] finding for fix instructions.']
              if any(isinstance(f, dict) and f.get('mode') == 'CV'
                     for f in findings)
              else []),
            *(['WARNING: System libraries required before pip install — see [CX] finding for install instructions.']
              if any(isinstance(f, dict) and f.get('mode') == 'CX'
                     for f in findings)
              else []),
            *(['WARNING: Authenticated cloud API required — '
               'credentials must be configured before running. '
               'See [CI] finding for account and authentication requirements.']
              if any(isinstance(f, dict) and f.get('mode') == 'CI'
                     and 'Authenticated' in f.get('title', '')
                     for f in findings)
              else [])
        ]),
        '',
        '---',
        '',
        f'*Generated by ValiChord Repository Readiness Check v15 — {now}*',
    ]

    out = output_dir / 'QUICKSTART_DRAFT.md'
    out.write_text('\n'.join(lines), encoding='utf-8-sig')
    print(f"  → QUICKSTART_DRAFT.md")


# ── LICENCE_DRAFT.txt ────────────────────────────────────────────────────────

def _generate_licence_draft(output_dir, all_files=None):
    """Generate LICENCE_DRAFT.txt."""

    now = datetime.now().strftime('%Y-%m-%d %H:%M')
    year = datetime.now().year

    content = f"""LICENCE_DRAFT.txt — generated by ValiChord Repository Readiness Check v15
Generated: {now}

YOU MUST COMPLETE THIS FILE before sharing your repository.

Choose one of the following options and replace this entire
file with your chosen licence text.

============================================================
RECOMMENDED FOR CODE: MIT Licence
============================================================

MIT License

Copyright (c) {year} [YOUR NAME]

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or
sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.

============================================================
RECOMMENDED FOR DATA: Creative Commons CC-BY 4.0
============================================================

If your repository includes data, consider licensing it under
Creative Commons Attribution 4.0 International (CC-BY 4.0).

See: https://creativecommons.org/licenses/by/4.0/

============================================================
IMPORTANT QUESTIONS TO ANSWER BEFORE CHOOSING:
============================================================

1. Does your data include human subjects data?
   If yes: do you have authorisation to share it?

2. Does your code use any GPL-licensed libraries?
   If yes: your code may need to be GPL-licensed too.

3. Does your institution have a default IP policy?
   If yes: check whether you need institutional approval.

4. Does your funder require a specific open licence?
   If yes: use that licence.

============================================================
Rename this file to LICENCE (no extension) or LICENCE.md
after completing it.
============================================================
"""

    out = output_dir / 'LICENCE_DRAFT.txt'
    out.write_text(content, encoding='utf-8-sig')
    print(f"  → LICENCE_DRAFT.txt")


# ── README placeholder ───────────────────────────────────────────────────────


def generate_proposed_corrections(repo_dir, all_files, findings, output_dir):
    """Generate corrected file copies in /proposed_corrections/."""

    corrections_dir = output_dir / 'proposed_corrections'
    corrections_dir.mkdir(exist_ok=True)

    # get all [C] absolute path findings
    path_findings = [f for f in findings if f['mode'] == 'C']

    if not path_findings:
        return

    # write a README for the corrections folder
    readme_lines = [
        '# proposed_corrections/',
        '',
        '> ⚠️ **THESE FILES CONTAIN A DELIBERATE RUNTIME ERROR.**',
        '> They will not execute until you remove the error block',
        '> at the top of each file.',
        '>',
        '> This is intentional. You must review each correction',
        '> before using it. The tool cannot guarantee that the',
        '> relative path replacements are correct for your setup.',
        '',
        '## How to use these files',
        '',
        '1. Open each file and read the correction at the top',
        '2. Verify the relative path is correct for your directory structure',
        '3. Remove the `raise RuntimeError` block at the top',
        '4. Replace the corresponding file in your repository',
        '5. Test that your code still runs correctly',
        '',
        '## Files corrected',
        '',
    ]

    corrected_files = []

    for path_finding in path_findings:
        # extract filename from evidence
        evidence = path_finding.get('evidence', [])
        if not evidence:
            continue

        fname = path_finding['detail']
        # find the actual file
        target_files = [
            f for f in all_files
            if path_finding['evidence'][0].startswith(
                f'Evidence: {f.name}'
            )
        ]

        if not target_files:
            continue

        src_file = target_files[0]

        try:
            content = src_file.read_text(encoding='utf-8', errors='ignore')
        except Exception:
            continue

        # find and replace absolute paths
        abs_pattern = re.compile(
            r'(/Users/[a-zA-Z][a-zA-Z0-9_\-]{1,}/[^\s\'")\]]*)'
            r'|(/home/[a-zA-Z][a-zA-Z0-9_\-]{1,}/[^\s\'")\]]*)'
            r'|(/root/[a-zA-Z][^\s\'")\]]*)'
            r'|([A-Z]:\\\\[A-Za-z][^\s\'")\]]*)'
            r'|([A-Z]:/[A-Za-z][^\s\'")\]]*)'
        )

        # Replace paths line-by-line, skipping ~/  and export PATH= lines
        # (mirrors the detection exclusions in detect_C_absolute_paths)
        corrected_lines = []
        replacements = []
        for _ln in content.splitlines(keepends=True):
            _s = _ln.strip()
            if '~/' in _s or re.match(r'export\s+\w*PATH\s*=', _s):
                corrected_lines.append(_ln)
                continue
            _line_matches = abs_pattern.findall(_ln)
            _line_flat = [m for grp in _line_matches for m in grp if m]
            for _m in _line_flat:
                _parts = _m.replace('\\', '/').rstrip('/').split('/')
                _suggested = './data/' + _parts[-1] if _parts else './data/file'
                _ln = _ln.replace(_m, _suggested, 1)
                replacements.append((_m, _suggested))
            corrected_lines.append(_ln)

        if not replacements:
            continue

        corrected = ''.join(corrected_lines)

        # build the warning block
        warning_lines = [
            '# ============================================================',
            '# VALICHORD PROPOSED CORRECTION — DO NOT RUN WITHOUT REVIEWING',
            '# ============================================================',
            '# This file was generated by ValiChord Repository Readiness Check.',
            '# The following absolute paths were detected and replaced',
            '# with suggested relative paths:',
            '#',
        ]
        for orig, sugg in replacements:
            warning_lines.append(f'#   ORIGINAL:  {orig}')
            warning_lines.append(f'#   SUGGESTED: {sugg}')
            warning_lines.append('#')
        warning_lines += [
            '# VERIFY each replacement before using this file.',
            '# The suggested paths may not match your directory structure.',
            '# ============================================================',
            '',
            'raise RuntimeError(',
            '    "VALICHORD PROPOSED CORRECTION: Remove this error block "',
            '    "after verifying the path corrections above."',
            ')',
            '',
            '# ============================================================',
            '',
        ]

        warning_block = '\n'.join(warning_lines) + '\n'
        final_content = warning_block + corrected

        out_file = corrections_dir / src_file.name
        out_file.write_text(final_content, encoding='utf-8-sig')
        corrected_files.append(src_file.name)

    # If no files were actually corrected (e.g. pattern mismatch between
    # detector and generator), skip writing the README entirely
    if not corrected_files:
        return

    # write the corrections README — consolidate duplicate filenames
    from collections import Counter
    file_counts = Counter(corrected_files)
    for fname, count in sorted(file_counts.items()):
        if count > 1:
            readme_lines.append(f'- `{fname}` ({count} corrections)')
        else:
            readme_lines.append(f'- `{fname}`')

    readme_lines += [
        '',
        '---',
        '',
        f'*Generated by ValiChord Repository Readiness Check v15*',
    ]

    readme_out = corrections_dir / 'README.md'
    readme_out.write_text('\n'.join(readme_lines), encoding='utf-8-sig')

    print(f"  → proposed_corrections/ ({len(corrected_files)} files)")