"""
ValiChord Auto-Generate
Draft File Generator
Produces all _DRAFT output files per ValiChord Specification v15
"""

from pathlib import Path
import re
from datetime import datetime
import re


CODE_EXTENSIONS = {
    '.py', '.r', '.rmd', '.qmd', '.jl', '.m', '.sh', '.bash', '.smk',
    '.do', '.sas', '.ado', '.c', '.cpp', '.f', '.f90',
    '.sql', '.rs', '.go', '.java', '.js', '.ts'
}

NOTEBOOK_EXTENSIONS = {'.ipynb', '.mlx', '.rmd', '.qmd'}

README_NAMES = {'readme.md', 'readme.txt', 'readme.rst', 'readme'}

DEPENDENCY_FILES = {
    'requirements.txt', 'requirements_extra.txt', 'environment.yml', 'environment.yaml',
    'pipfile.lock', 'poetry.lock', 'setup.py', 'pyproject.toml',
    'renv.lock', 'cargo.toml', 'package.json'
}


def generate_all_drafts(repo_dir, all_files, findings, output_dir):
    """Generate all _DRAFT files."""

    modes_found = {f['mode'] for f in findings}

    has_code = any(f.suffix.lower() in CODE_EXTENSIONS or f.suffix.lower() == '.ipynb' for f in all_files)
    _generate_inventory(repo_dir, all_files, output_dir)
    _generate_readme_draft(repo_dir, all_files, findings, output_dir)
    if has_code:
        _generate_requirements_draft(repo_dir, all_files,
                                      findings, output_dir)
        _generate_quickstart_draft(repo_dir, all_files,
                                    findings, output_dir)
    _generate_licence_draft(output_dir, all_files)
    generate_proposed_corrections(repo_dir, all_files, findings, output_dir)


# ── INVENTORY_DRAFT.md ───────────────────────────────────────────────────────

def _generate_inventory(repo_dir, all_files, output_dir):
    """Generate INVENTORY_DRAFT.md — full file listing."""

    now = datetime.now().strftime('%Y-%m-%d %H:%M')
    lines = [
        '# ValiChord Repository Readiness Check — File Inventory',
        '',
        f'**Generated:** {now}',
        f'**Total files:** {len(all_files)}',
        '',
        '> This inventory was generated by automated analysis.',
        '> File purpose descriptions are structural only — '
        'derived from',
        '> code evidence where available. Semantic descriptions',
        '> are not inferred from filenames.',
        '',
        '---',
        '',
        '## File Listing',
        '',
        '| File | Type | Size | Notes |',
        '|---|---|---|---|',
    ]

    for f in sorted(all_files, key=lambda x: str(x)):
        rel = f.relative_to(repo_dir)
        size = f.stat().st_size
        size_str = (f'{size:,} bytes' if size < 10240
                    else f'{size/1024:.1f} KB')
        ftype = _classify_file(f)
        notes = _file_notes(f)
        lines.append(f'| `{rel}` | {ftype} | {size_str} | {notes} |')

    lines += [
        '',
        '---',
        '',
        f'*Generated by ValiChord Repository Readiness Check — v15 — {now}*',
    ]

    out = output_dir / 'INVENTORY_DRAFT.md'
    out.write_text('\n'.join(lines), encoding='utf-8-sig')
    print(f"  → INVENTORY_DRAFT.md ({len(all_files)} files)")


def _classify_file(f):
    ext = f.suffix.lower()
    if ext in CODE_EXTENSIONS:
        return 'Code'
    if ext in NOTEBOOK_EXTENSIONS:
        return 'Notebook'
    if ext in {'.md', '.txt', '.rst', '.html', '.tex'}:
        return 'Documentation'
    if ext in {'.csv', '.tsv', '.xlsx', '.json', '.parquet',
               '.rds', '.rdata', '.dta', '.sav', '.mat',
               '.pkl', '.npy', '.npz', '.hdf5', '.h5'}:
        return 'Data'
    if ext in {'.png', '.jpg', '.jpeg', '.pdf', '.svg', '.tif'}:
        return 'Figure/Image'
    if f.name.lower() == 'citation.cff':
        return 'Citation'
    if f.name.lower() in DEPENDENCY_FILES:
        return 'Dependency spec'
    if ext in {'.yml', '.yaml', '.toml', '.ini', '.cfg'}:
        return 'Configuration'
    if ext in {'.sh', '.bash'}:
        return 'Shell script'
    if ext in {'.gpg', '.enc', '.secret', '.age', '.asc'}:
        return '⚠️ POSSIBLY ENCRYPTED'
    if f.name == 'Snakefile' or f.suffix.lower() == '.smk':
        return 'Workflow'
    return 'Other'


def _file_notes(f):
    name = f.name.lower()
    ext = f.suffix.lower()
    if ext in {'.gpg', '.enc', '.secret', '.age', '.asc'}:
        return '🔴 POSSIBLY ENCRYPTED — may be unusable without key'
    if name == 'citation.cff':
        return 'CITATION.cff — check all required fields are complete'
    if 'codebook' in name or 'data_dictionary' in name or 'data_dict' in name:
        return 'Codebook / data dictionary'
    if name in README_NAMES:
        return 'README'
    if name in {'licence', 'license', 'licence.md',
                'license.md', 'licence.txt', 'license.txt'}:
        return 'Licence file'
    import re as _ren
    if _ren.match(r'requirements.*\.txt$', name):
        return 'Dependency specification'
    if name == 'dockerfile':
        return 'Container definition'
    if re.match(r'^0*[0-9]+[_\-]', f.name):
        return 'Numbered script — execution order implied'
    return ''


# ── README_DRAFT.md ──────────────────────────────────────────────────────────


def _readme_install_block(all_files, r_packages=None, github_pkgs=None):
    """Return language-appropriate installation instructions for README_DRAFT."""
    if github_pkgs is None:
        github_pkgs = {}
    suffixes = {f.suffix.lower() for f in all_files}
    if any(f.name == 'Snakefile' for f in all_files):
        suffixes.add('.smk')
    names = {f.name.lower() for f in all_files}
    # data-only deposit — no code present
    has_code = any(s in suffixes for s in {".py", ".r", ".jl", ".do", ".m", ".rmd", ".smk", ".ipynb"})
    if not has_code:
        codebook = next((f.name for f in all_files if "codebook" in f.name.lower() or "data_dict" in f.name.lower()), None)
        return [
            "# This is a data-only deposit. No code execution is required.",
            "# Files are provided in standard formats (CSV, Excel, etc.)",
            f"# See {codebook} for variable descriptions." if codebook else "# See the codebook for variable descriptions.",
        ]
    # conda repo — takes precedence over all language-specific checks
    if 'environment.yml' in names or 'environment.yaml' in names:
        env_file = 'environment.yml' if 'environment.yml' in names else 'environment.yaml'
        env_name = 'myenv'
        env_path = next((f for f in all_files if f.name.lower() == env_file), None)
        if env_path:
            import re as _re
            m = _re.search(r'^name:\s*(\S+)', env_path.read_text(encoding='utf-8', errors='ignore'), _re.MULTILINE)
            if m:
                env_name = m.group(1)
        return [
            '# 1. Clone or download this repository',
            '# 2. Create and activate the conda environment',
            f'conda env create -f {env_file}',
            f'conda activate {env_name}',
        ]
    # Docker repo — takes priority over language-specific blocks
    if 'dockerfile' in names:
        return [
            '# 1. Build the Docker image',
            'docker build -t my-analysis .',
            '# 2. Run the container (mount data directory)',
            'docker run -v $(pwd)/data:/app/data my-analysis',
            '# Or with an interactive shell:',
            '# docker run -it -v $(pwd)/data:/app/data my-analysis bash',
        ]
    if '.jl' in suffixes:
        if 'project.toml' in names:
            return [
                '# 1. Clone or download this repository',
                '# 2. Install Julia dependencies',
                'julia --project=. -e "using Pkg; Pkg.instantiate()"',
            ]
        else:
            # Check for embedded Pluto manifest — if present, just open in Pluto
            pluto_files = [f for f in all_files if f.suffix.lower() == '.jl']
            has_pluto_deps = any(
                'PLUTO_PROJECT_TOML_CONTENTS' in f.read_text(encoding='utf-8', errors='ignore')
                for f in pluto_files
            )
            if has_pluto_deps:
                return [
                    '# 1. Clone or download this repository',
                    '# 2. Open the notebook in Pluto — dependencies are embedded',
                    '# julia -e \'using Pkg; Pkg.add(\"Pluto\"); using Pluto; Pluto.run()\'',
                    '# Then open the .jl notebook file — Pluto will install dependencies automatically',
                ]
            # No Pluto, no Project.toml — extract packages dynamically
            import re as _re
            julia_stdlib_set = {'Random','Statistics','LinearAlgebra','Dates','Printf',
                                'Base','Core','Main','Pkg','Test','Logging','REPL',
                                'InteractiveUtils','Distributed','Serialization',
                                'Markdown','Unicode','DelimitedFiles','SparseArrays'}
            jl_pkgs = sorted({
                pkg.strip()
                for f in pluto_files
                for line in f.read_text(encoding='utf-8', errors='ignore').splitlines()
                for m in [_re.match(r'^using\s+([\w,\s]+)', line.strip())]
                if m
                for pkg in _re.split(r'[,\s]+', m.group(1))
                if pkg.strip() and pkg.strip() not in julia_stdlib_set
            })
            if jl_pkgs:
                pkg_list = ', '.join(f'\"{p}\"' for p in jl_pkgs)
                return [
                    '# 1. Clone or download this repository',
                    '# 2. Install required Julia packages',
                    f'julia -e \'using Pkg; Pkg.add([{pkg_list}])\'',
                ]
            return [
                '# 1. Clone or download this repository',
                '# 2. Install required Julia packages manually using Pkg.add()',
            ]
    if '.r' in suffixes or '.rmd' in suffixes:
        has_python = '.py' in suffixes
        if 'renv.lock' in names:
            if has_python:
                return [
                    '# 1. Clone or download this repository',
                    '# 2. Set up Python environment',
                    'python -m venv venv',
                    'source venv/bin/activate  # Windows: venv\\Scripts\\activate',
                    'pip install -r requirements.txt',
                    '# 3. Restore R environment',
                    'Rscript -e "renv::restore()"',
                ]
            return [
                '# 1. Clone or download this repository',
                '# 2. Restore R environment',
                'Rscript -e "renv::restore()"',
            ]
        pkgs = r_packages or ['dplyr', 'ggplot2']
        cran_pkgs = [p for p in pkgs if p.lower() not in github_pkgs]
        gh_only = [p for p in pkgs if p.lower() in github_pkgs]
        pkg_str = ', '.join("'" + p + "'" for p in cran_pkgs) if cran_pkgs else None
        gh_lines = [f"Rscript -e \"devtools::install_github('{github_pkgs.get(p.lower(), p).strip(chr(39)).strip(chr(34))}')\"" for p in gh_only]
        block = ['# 1. Clone or download this repository']
        if has_python:
            block += ['# 2. Set up Python environment',
                      'python -m venv venv',
                      'source venv/bin/activate  # Windows: venv\\Scripts\\activate',
                      'pip install -r requirements.txt']
            step = 3
        else:
            step = 2
        if pkg_str:
            block.append(f'# {step}. Install CRAN packages')
            block.append(f'Rscript -e "install.packages(c({pkg_str}))".format()' if False else f'Rscript -e "install.packages(c({pkg_str}))"')
            step += 1
        if gh_lines:
            block.append(f'# {step}. Install GitHub packages')
            block += gh_lines
        return block
    if '.do' in suffixes or '.ado' in suffixes:
        return [
            '# 1. Clone or download this repository',
            '# 2. Install required Stata packages via ssc install',
        ]
    if '.m' in suffixes:
        eeglab_fns = {'pop_epoch', 'pop_autorej', 'pop_resample', 'pop_eegfiltnew',
                      'eeglab', 'pop_loadset', 'pop_saveset', 'runica'}
        has_eeglab = any(
            any(fn in f.read_text(encoding='utf-8', errors='ignore') for fn in eeglab_fns)
            for f in all_files if f.suffix.lower() == '.m'
        )
        block = [
            '# 1. Open MATLAB (see README for required version)',
            '# 2. Ensure required toolboxes are licensed and installed',
        ]
        if has_eeglab:
            block += [
                '# 3. Add EEGLAB folder to your MATLAB path',
                '#    addpath(genpath("/path/to/eeglab"))',
                '# 4. Open and run the main script',
            ]
        else:
            block.append('# 3. Open and run the main script')
        return block
    # conda repo — environment.yml present
    if 'environment.yml' in names or 'environment.yaml' in names:
        env_file = 'environment.yml' if 'environment.yml' in names else 'environment.yaml'
        # Try to extract conda env name
        env_name = 'myenv'
        env_path = next((f for f in all_files if f.name.lower() == env_file), None)
        if env_path:
            import re as _re
            m = _re.search(r'^name:\s*(\S+)', env_path.read_text(encoding='utf-8', errors='ignore'), _re.MULTILINE)
            if m:
                env_name = m.group(1)
        return [
            '# 1. Clone or download this repository',
            '# 2. Create and activate the conda environment',
            f'conda env create -f {env_file}',
            f'conda activate {env_name}',
        ]
    # default Python
    return [
        '# 1. Clone or download this repository',
        '# 2. Create a virtual environment',
        'python -m venv venv',
        'source venv/bin/activate  # Windows: venv\\Scripts\\activate',
        '',
        '# 3. Install dependencies',
        '# First ensure all version numbers are pinned in requirements.txt',
        'pip install -r requirements.txt',
    ]

def _generate_readme_draft(repo_dir, all_files, findings, output_dir):
    """Generate README_DRAFT.md."""

    now = datetime.now().strftime('%Y-%m-%d %H:%M')

    # try to find existing readme content
    existing_readme = ''
    for f in all_files:
        if f.name.lower() in README_NAMES:
            try:
                existing_readme = f.read_text(
                    encoding='utf-8', errors='ignore'
                )
            except Exception:
                pass
            break

    # assess whether existing readme is adequate
    readme_adequate = False
    if existing_readme and len(existing_readme.strip()) > 500:
        key_sections = ['installation', 'usage', 'data', 'run', 'reproduce', 'requirement']
        sections_found = sum(1 for s in key_sections if s in existing_readme.lower())
        if sections_found >= 2:
            readme_adequate = True

    if readme_adequate:
        # existing README is reasonable — just note what's missing
        readme_findings = [f for f in findings if f.get('mode') in ('A', 'G', 'Z', 'K', 'N', 'E', 'Y')]
        lines = [
            '# README Review Notes',
            '',
            '> ⚠️ **README_DRAFT.md** — Your existing README appears adequate.',
            '> This file only lists items that may need attention.',
            '> Your original README has been preserved — do not replace it with this file.',
            '',
            '---',
            '',
            '## Items to check in your existing README',
            '',
        ]
        if readme_findings:
            for f in readme_findings:
                lines.append(f'- {f.get("title", "")}')
        else:
            lines.append('- No specific README gaps detected.')
        lines += [
            '',
            '---',
            '',
            '## Your existing README (for reference)',
            '',
            existing_readme,
        ]
        out = output_dir / 'README_DRAFT.md'
        out.write_text('\n'.join(lines), encoding='utf-8-sig')
        print(f"  → README_DRAFT.md (existing README adequate)")
        return

    # extract R packages for install block
    r_pkgs = set()
    github_pkgs = {}  # pkg_name_lower -> 'owner/repo'
    lib_pat = re.compile(r'(?:library|require)\s*\(\s*["\']?([\w\.]+)["\']?\s*\)')
    github_pat = re.compile(r'(?:devtools|remotes)::install_github\s*\(\s*["\']([^"\'/]+/([\w.-]+))["\']', re.IGNORECASE)
    for rf in [f for f in all_files if f.suffix.lower() in {'.r', '.rmd', '.qmd'}]:
        for m in lib_pat.finditer(rf.read_text(encoding='utf-8', errors='ignore')):
            r_pkgs.add(m.group(1))
    for rf in all_files:
        if re.match(r'(install|setup).*\.r$', rf.name.lower()):
            try:
                src = rf.read_text(encoding='utf-8', errors='ignore')
                for m in github_pat.finditer(src):
                    github_pkgs[m.group(2).lower()] = m.group(1)
            except Exception:
                pass
    has_code = any(f.suffix.lower() in CODE_EXTENSIONS or f.suffix.lower() == '.ipynb' or f.name == 'Snakefile' for f in all_files)
    if not has_code:
        # data-only deposit — use data-focused template
        data_files = [f for f in all_files if f.suffix.lower() in {".csv", ".tsv", ".xlsx", ".xls", ".dta", ".sav", ".json", ".parquet"}]
        codebook = next((f.name for f in all_files if "codebook" in f.name.lower() or "data_dict" in f.name.lower()), None)
        lines = [
            '# [TITLE OF DATASET — YOU MUST COMPLETE THIS]',
            '',
            '> ⚠️ **README_DRAFT.md** — Generated by ValiChord. Complete all sections then rename to `README.md`.',
            '',
            '---',
            '',
            '## Dataset Identification',
            '',
            '- **Dataset title:** [YOU MUST COMPLETE THIS]',
            '- **Authors/collectors:** [YOU MUST COMPLETE THIS]',
            '- **Associated paper DOI:** [YOU MUST COMPLETE THIS]',
            '- **Date of deposit:** ' + datetime.now().strftime('%Y-%m-%d'),
            '- **Licence:** [e.g. CC BY 4.0]',
            '',
            '---',
            '',
            '## Dataset Overview',
            '',
            '[YOU MUST COMPLETE THIS — describe what this dataset contains, how it was collected, and what research it supports.]',
            '',
            '---',
            '',
            '## Data Files',
            '',
            '| File | Format | Description | Rows | Variables |',
            '|---|---|---|---|---|',
            *[f'| `{f.name}` | {f.suffix.upper().lstrip(".")} | [YOU MUST COMPLETE THIS] | | |' for f in data_files],
            '',
            '---',
            '',
            '## Variables',
            '',
            f'See `{codebook}` for full variable descriptions.' if codebook else '[YOU MUST COMPLETE THIS — list all variables or reference your codebook.]',
            '',
            '---',
            '',
            '## Collection Methodology',
            '',
            '[YOU MUST COMPLETE THIS — describe how data was collected, survey instruments, sampling strategy, dates of collection.]',
            '',
            '---',
            '',
            '## Access Conditions',
            '',
            '[YOU MUST COMPLETE THIS — state whether data is open access, restricted, or embargoed. If restricted, who to contact.]',
            '',
            '---',
            '',
            '## File Integrity',
            '',
            '[YOU MUST COMPLETE THIS — provide SHA-256 checksums for all data files.]',
            '',
            '| File | SHA-256 |',
            '|---|---|',
            *[f'| `{f.name}` | [checksum] |' for f in data_files],
            '',
            '---',
            '',
            f'*Generated by ValiChord Repository Readiness Check — {datetime.now().strftime("%Y-%m-%d %H:%M")}*',
        ]
        if existing_readme:
            lines += ["", "---", "", "## Original README (for reference)", "", existing_readme]
        out = output_dir / "README_DRAFT.md"
        out.write_text("\n".join(lines), encoding="utf-8-sig")
        print("  → README_DRAFT.md (data-only template)")
        return
    lines = [
        '# [TITLE OF PAPER — YOU MUST COMPLETE THIS]',
        '',
        '> ⚠️ **README_DRAFT.md** — This file was generated by '
        'ValiChord Repository Readiness Check.',
        '> All sections marked [YOU MUST COMPLETE THIS] require '
        'your input.',
        '> Verify all content, then rename to `README.md`.',
        '',
        '---',
        '',
        '## Study Identification',
        '',
        '- **Paper title:** [YOU MUST COMPLETE THIS]',
        '- **Authors:** [YOU MUST COMPLETE THIS]',
        '- **DOI / URL:** [YOU MUST COMPLETE THIS]',
        '- **Date of deposit:** '
        f'{datetime.now().strftime("%Y-%m-%d")}',
        '- **Commit hash / version tag:** '
        '[YOU MUST COMPLETE THIS — e.g. git rev-parse HEAD]',
        '',
        '---',
        '',
        '## Study Overview',
        '',
        '[YOU MUST COMPLETE THIS — 2 to 5 sentences describing '
        'what this repository does and what paper it supports. '
        'This cannot be generated automatically.]',
        '',
        '---',
        '',
        '## System Requirements',
        '',
        '- **Operating system:** [e.g. Ubuntu 22.04 / macOS 13 '
        '/ Windows 11]',
        '- **Programming language:** [e.g. Python 3.11.2]',
        '- **RAM required:** [e.g. 16GB minimum]',
        '- **GPU required:** [Yes/No — if yes, specify model]',
        '- **Estimated runtime:** [e.g. 2 hours on 8-core laptop]',
        '- **HPC required:** [Yes/No — if yes, specify nodes/cores]',
        '',
        '---',
        '',
        '## Installation',
        '',
        '```bash',
        *_readme_install_block(all_files, sorted(r_pkgs) if r_pkgs else None, github_pkgs=github_pkgs),
        '```',
        '',
        '[YOU MUST COMPLETE THIS — add any additional '
        'installation steps]',
        '',
        '---',
        '',
        '## Execution',
        '',
        '[YOU MUST COMPLETE THIS — describe the steps to run '
        'your analysis]',
        '',
        'See `QUICKSTART_DRAFT.md` for an inferred execution '
        'order (verify before using).',
        '',
        '---',
        '',
        '## Data',
        '',
        '- **Data location:** [describe where data files are]',
        '- **Data source:** [YOU MUST COMPLETE THIS]',
        '- **Data version:** [YOU MUST COMPLETE THIS — '
        'exact version/date of any external dataset]',
        '- **Anonymised/synthetic:** [Yes/No — if yes, '
        'describe transformation]',
        '',
        '---',
        '',
        '## Expected Outputs',
        '',
        '[YOU MUST COMPLETE THIS — describe what a validator '
        'should see after running your code]',
        '',
        '### Figure to file mapping',
        '',
        '[YOU MUST COMPLETE THIS — the tool cannot infer '
        'which scripts produce which figures]',
        '',
        '| Paper Figure | Generated File | Producing Script |',
        '|---|---|---|',
        '| Figure 1 | | |',
        '| Figure 2 | | |',
        '',
        '---',
        '',
        '## Definition of Successful Reproduction',
        '',
        '> ⚠️ **YOU MUST COMPLETE THIS SECTION.**',
        '> State exactly what constitutes successful reproduction.',
        '> Include numerical values and tolerance bands.',
        '',
        '[YOU MUST COMPLETE THIS]',
        '',
        '---',
        '',
        '## Known Issues and Limitations',
        '',
        '[YOU MUST COMPLETE THIS — document any platform '
        'sensitivity, stochasticity, or known reproduction '
        'limitations]',
        '',
        '---',
        '',
        '## Licence',
        '',
        'See `LICENCE_DRAFT.txt` (verify and rename to LICENCE).',
        '',
        '---',
        '',
        '## Contact',
        '',
        '[YOU MUST COMPLETE THIS — who should validators '
        'contact if reproduction fails?]',
        '',
        '---',
        '',
        f'*README_DRAFT.md generated by ValiChord Repository Readiness Check v15 — {now}*',
        '*Verify all content before removing _DRAFT from filename.*',
    ]

    # append original readme if it existed but was inadequate
    if existing_readme and len(existing_readme.strip()) > 50:
        lines += [
            '',
            '---',
            '',
            '## Original README Content (for reference)',
            '',
            '> The following is the original README content.',
            '> Use it to fill in the sections above.',
            '',
            existing_readme,
        ]

    out = output_dir / 'README_DRAFT.md'
    out.write_text('\n'.join(lines), encoding='utf-8-sig')
    print(f"  → README_DRAFT.md")


# ── requirements_DRAFT.txt ───────────────────────────────────────────────────

def _generate_requirements_draft(repo_dir, all_files,
                                   findings, output_dir):
    """Generate requirements_DRAFT.txt from import statements."""

    # preserve existing requirements_DRAFT.txt from prior run
    prior_draft = next((f for f in all_files if f.name.lower() == "requirements_draft.txt"), None)
    if prior_draft:
        prior_content = prior_draft.read_text(encoding="utf-8", errors="ignore")
        out = output_dir / "requirements_DRAFT.txt"
        out.write_text(
            "# Prior requirements_DRAFT.txt preserved from previous ValiChord run.\n"
            "# Review and pin all versions before renaming to requirements.txt.\n"
            "#\n" + prior_content, encoding="utf-8-sig")
        print("  -> requirements_DRAFT.txt (preserved from prior run)")
        return
    # Collect all requirements*.txt files to handle requirements_extra.txt etc.
    import re as _re2
    req_files_all = sorted(
        [f for f in all_files if _re2.match(r'requirements.*\.txt$', f.name.lower())],
        key=lambda x: x.name
    )
    if req_files_all:
        combined_lines = []
        for rf in req_files_all:
            try:
                rf_lines = rf.read_text(encoding='utf-8', errors='ignore').splitlines()
                combined_lines.append(f'# --- {rf.name} ---')
                combined_lines += rf_lines
            except Exception:
                pass
        combined = '\n'.join(combined_lines)
        pinned = [l for l in combined_lines if '==' in l and not l.strip().startswith('#')]
        unpinned_git = [l for l in combined_lines if l.strip().startswith('git+')]
        loose = [l for l in combined_lines if _re2.match(r'[\w.-]+\s*[><!]=', l.strip()) and '==' not in l]
        has_issues = unpinned_git or loose
        if pinned and not has_issues:
            out = output_dir / 'requirements_DRAFT.txt'
            msg = ('# All requirements files: ' + ', '.join(f.name for f in req_files_all) + '\n'
                   '# ' + str(len(pinned)) + ' pinned packages found.\n'
                   '# Verify versions are correct before deposit.\n#\n' + combined)
            out.write_text(msg, encoding='utf-8-sig')
            return
        elif combined_lines:
            out = output_dir / 'requirements_DRAFT.txt'
            notes = []
            if unpinned_git:
                notes.append('# WARNING: git+ URLs present — pin to commit SHA for reproducibility')
            if loose:
                notes.append('# WARNING: loose version constraints present — pin to exact versions')
            msg = ('# Combined from: ' + ', '.join(f.name for f in req_files_all) + '\n'
                   + '\n'.join(notes) + ('\n' if notes else '')
                   + '# Review and pin all versions before deposit.\n#\n' + combined)
            out.write_text(msg, encoding='utf-8-sig')
            return
    for dep_file in all_files:
        if dep_file.name.lower() in DEPENDENCY_FILES:
            try:
                existing = dep_file.read_text(encoding="utf-8", errors="ignore")
                pinned = [l for l in existing.splitlines() if "==" in l and not l.strip().startswith("#")]
                if pinned:
                    out = output_dir / "requirements_DRAFT.txt"
                    msg = ("# Existing file: " + dep_file.name + "\n"
                           "# " + str(len(pinned)) + " pinned packages found - no DRAFT needed.\n"
                           "# Verify versions are correct before deposit.\n#\n" + existing)
                    out.write_text(msg, encoding="utf-8-sig")
                    return
                else:
                    # existing file found but versions unpinned
                    if dep_file.name.lower() == "pyproject.toml":
                        # extract only dependencies from [project] section
                        import re as _re
                        dep_section = _re.search(
                            r'dependencies\s*=\s*\[([^\]]+)\]', existing, _re.DOTALL)
                        if dep_section:
                            raw_deps = dep_section.group(1)
                            pkgs = _re.findall(r'["\']([a-zA-Z][a-zA-Z0-9_\-\.]*)', raw_deps)
                            bounds = _re.findall(r'["\']([a-zA-Z][^"\']*)["\']\s*,?', raw_deps)
                            out = output_dir / "requirements_DRAFT.txt"
                            lines_out = [
                                "# pyproject.toml detected — dependencies extracted from [project] dependencies",
                                "# These have minimum version bounds but need exact pinning for reproducibility.",
                                "#", ""]
                            for b in bounds:
                                b = b.strip()
                                if b and not b.startswith("#"):
                                    lines_out.append(b + "  # pin to exact version")
                            out.write_text("\n".join(lines_out), encoding="utf-8-sig")
                            return
                    packages = [l.strip() for l in existing.splitlines()
                                if l.strip() and not l.strip().startswith("#")
                                and "=" in l and "[" not in l and "]" not in l]
                    if packages:
                        out = output_dir / "requirements_DRAFT.txt"
                        lines_out = ["# Existing " + dep_file.name + " found but versions are NOT pinned.",
                                     "# Add exact version numbers (e.g. pandas==2.1.3) before deposit.",
                                     "#", "# Current contents:", ""]
                        # Try to extract version bounds from embedded Pluto TOML
                        pluto_versions = {}
                        for jl_f in all_files:
                            if jl_f.suffix.lower() == '.jl':
                                jl_src = jl_f.read_text(encoding='utf-8', errors='ignore')
                                compat_m = re.search(r'\[compat\](.*?)(?:\[|$)', jl_src, re.DOTALL)
                                if compat_m:
                                    for vm in re.finditer(r'^(\w[\w\.]+)\s*=\s*"([^"]+)"', compat_m.group(1), re.MULTILINE):
                                        pluto_versions[vm.group(1).lower()] = vm.group(2)
                        def _pin_or_unknown(p):
                            if "==" in p or p.startswith("#"):
                                return p
                            pkg_name = p.split("==")[0].split(">=")[0].split("~=")[0].strip()
                            ver = pluto_versions.get(pkg_name.lower())
                            if ver:
                                return f"{pkg_name}>={ver.lstrip('~^')}  # from embedded Pluto compat block"
                            return p + "==UNKNOWN"
                        lines_out += [_pin_or_unknown(p) for p in packages]
                        out.write_text("\n".join(lines_out), encoding="utf-8-sig")
                        return
            except Exception:
                pass
    imports = set()

    import ast as _ast
    # scan .ipynb notebooks for imports
    import json as _json
    for f in all_files:
        if f.suffix.lower() == '.ipynb':
            try:
                nb = _json.loads(f.read_text(encoding='utf-8', errors='ignore'))
                for cell in nb.get('cells', []):
                    if cell.get('cell_type') == 'code':
                        src = ''.join(cell.get('source', []))
                        for line in src.splitlines():
                            line = line.strip()
                            m = re.match(r'^import\s+([\w]+)', line)
                            if m: imports.add(m.group(1))
                            m = re.match(r'^from\s+([\w]+)', line)
                            if m: imports.add(m.group(1))
            except Exception:
                pass
    for f in all_files:
        if f.suffix.lower() == '.py':
            try:
                src = f.read_text(encoding='utf-8', errors='ignore')
                try:
                    tree = _ast.parse(src)
                    for node in _ast.walk(tree):
                        if isinstance(node, _ast.Import):
                            for alias in node.names:
                                imports.add(alias.name.split('.')[0])
                        elif isinstance(node, _ast.ImportFrom):
                            if node.module:
                                imports.add(node.module.split('.')[0])
                except SyntaxError:
                    for line in src.splitlines():
                        line = line.strip()
                        m = re.match(r'^import\s+([\w]+)', line)
                        if m:
                            imports.add(m.group(1))
                        m = re.match(r'^from\s+([\w]+)', line)
                        if m:
                            imports.add(m.group(1))
            except Exception:
                pass

    # scan .jl / Pluto notebooks for 'using' statements
    julia_stdlib = {'Random', 'Statistics', 'LinearAlgebra', 'Dates', 'Printf',
                    'Base', 'Core', 'Main', 'Pkg', 'Test', 'Logging', 'REPL',
                    'InteractiveUtils', 'Distributed', 'Serialization',
                    'Markdown', 'Unicode', 'DelimitedFiles', 'SparseArrays',
                    'SharedArrays', 'Mmap', 'Profile', 'FileWatching'}
    julia_imports = set()
    for f in all_files:
        if f.suffix.lower() in {'.jl'}:
            try:
                src = f.read_text(encoding='utf-8', errors='ignore')
                for line in src.splitlines():
                    line = line.strip()
                    m = re.match(r'^using\s+([\w,\s]+)', line)
                    if m:
                        for pkg in re.split(r'[,\s]+', m.group(1)):
                            pkg = pkg.strip()
                            if pkg and pkg not in julia_stdlib:
                                julia_imports.add(pkg)
            except Exception:
                pass
    # Julia imports added after Python stdlib filter (see below)
    # filter out stdlib and local modules
    stdlib = {
        'os', 'sys', 're', 'math', 'json', 'csv', 'io',
        'time', 'datetime', 'pathlib', 'shutil', 'tempfile',
        'collections', 'itertools', 'functools', 'operator',
        'string', 'random', 'copy', 'abc', 'typing',
        'dataclasses', 'enum', 'warnings', 'logging',
        'unittest', 'subprocess', 'threading', 'multiprocessing',
        'argparse', 'configparser', 'hashlib', 'base64',
        'urllib', 'http', 'email', 'html', 'xml', 'sqlite3',
        'pickle', 'struct', 'array', 'queue', 'socket',
        'ssl', 'uuid', 'platform', 'inspect', 'importlib',
        'ast', 'dis', 'traceback', 'contextlib', 'weakref',
        'gc', 'ctypes', 'builtins', 'types', 'textwrap',
        'pprint', 'glob', 'fnmatch', 'stat', 'pwd', 'grp',
        'zipfile', 'tarfile', 'gzip', 'bz2', 'lzma',
        'zlib', 'binascii', 'codecs',
    }

    # local python files in repo
    local_modules = {
        f.stem.lower() for f in all_files
        if f.suffix.lower() == '.py'
    }

    external = sorted(
        imp for imp in imports
        if imp.lower() not in stdlib
        and imp.lower() not in local_modules
        and not imp.startswith('_')
    )
    # Merge Julia imports after Python stdlib filter so CSV etc. aren't excluded
    external = sorted(set(external) | {pkg for pkg in julia_imports if not pkg.startswith('_')})

    now = datetime.now().strftime('%Y-%m-%d %H:%M')

    lines = [
        '# ============================================================',
        '# DEPENDENCY EXTRACTION NOTICE',
        '# Generated by ValiChord Repository Readiness Check v15',
        '#',
        '# These package names were inferred from import statements',
        '# by static analysis. This list is NOT authoritative.',
        '#',
        '# - Local module names have been excluded',
        '# - Standard library modules have been excluded',
        '# - ALL VERSION NUMBERS ARE UNKNOWN',
        '#   You must supply exact versions before this file',
        '#   can be used for reproduction',
        '# - This list may include optional or unused packages',
        '# - This list may miss dynamically imported packages',
        '#',
        f'# Generated: {now}',
        '# ============================================================',
        '',
    ]

    # detect language-specific dependency systems
    all_suffixes = {f.suffix.lower() for f in all_files}
    if any(f.name == 'Snakefile' for f in all_files):
        all_suffixes.add('.smk')
    all_names = {f.name.lower() for f in all_files}

    # Extract version bounds from Project.toml [compat] or embedded Pluto TOML
    pluto_compat = {}
    # Standard Project.toml
    for toml_f in all_files:
        if toml_f.name.lower() == 'project.toml':
            try:
                toml_src = toml_f.read_text(encoding='utf-8', errors='ignore')
                compat_m = re.search(r'\[compat\](.*?)(?:\[|$)', toml_src, re.DOTALL)
                if compat_m:
                    for vm in re.finditer(r'^(\w[\w.]+)\s*=\s*"([^"]+)"', compat_m.group(1), re.MULTILINE):
                        pluto_compat[vm.group(1).lower()] = vm.group(2).lstrip('~^')
            except Exception:
                pass
    # Embedded Pluto TOML (overrides if present)
    for jl_f in all_files:
        if jl_f.suffix.lower() == '.jl':
            try:
                jl_src = jl_f.read_text(encoding='utf-8', errors='ignore')
                compat_m = re.search(r'\[compat\](.*?)(?:\[|$)', jl_src, re.DOTALL)
                if compat_m:
                    for vm in re.finditer(r'^(\w[\w.]+)\s*=\s*"([^"]+)"', compat_m.group(1), re.MULTILINE):
                        pluto_compat[vm.group(1).lower()] = vm.group(2).lstrip('~^')
            except Exception:
                pass
    if external:
        for pkg in external:
            ver = pluto_compat.get(pkg.lower())
            if ver:
                lines.append(f'{pkg}>={ver}  # from Project.toml or Pluto [compat] — not an exact pin')
            else:
                lines.append(f'{pkg}==UNKNOWN')
    elif 'project.toml' in all_names and '.jl' in all_suffixes:
        lines += [
            '# Julia repository detected.',
            '# Dependencies are managed by Project.toml and Manifest.toml.',
            '# No requirements_DRAFT.txt needed.',
            '# To install: julia --project=. -e "using Pkg; Pkg.instantiate()"',
        ]
    elif 'renv.lock' in all_names or '.r' in all_suffixes:
        r_files = [f for f in all_files if f.suffix.lower() in {'.r', '.rmd', '.qmd'}]
        r_libs = set()
        lib_pat = re.compile(r'(?:library|require)\s*\(\s*["\']?([\w\.]+)["\']?\s*\)')
        for rf in r_files:
            for m in lib_pat.finditer(rf.read_text(encoding='utf-8', errors='ignore')):
                r_libs.add(m.group(1))
        # Build github_pkgs map from install*.R scripts
        _ghpat = re.compile(r'(?:devtools|remotes)::install_github\s*\(\s*["\']([^"\'/]+/([\w.-]+))["\']', re.IGNORECASE)
        gh_map = {}
        for _rf in all_files:
            if re.match(r'(install|setup).*\.r$', _rf.name.lower()):
                try:
                    for _m in _ghpat.finditer(_rf.read_text(encoding='utf-8', errors='ignore')):
                        gh_map[_m.group(2).lower()] = _m.group(1)
                except Exception:
                    pass
        if r_libs:
            cran_list = [p for p in sorted(r_libs) if p.lower() not in gh_map]
            gh_list = [p for p in sorted(r_libs) if p.lower() in gh_map]
            lines += ['# R repository detected.',
                      '# Packages detected from library()/require() calls:',
                      '# Add version numbers before deposit.', '']
            if cran_list:
                lines.append('# CRAN packages:')
                lines += [f'{pkg}  # version unknown' for pkg in cran_list]
            if gh_list:
                if cran_list:
                    lines.append('')
                lines.append('# GitHub packages (no CRAN release -- pinning required):')
                for pkg in gh_list:
                    repo = gh_map.get(pkg.lower(), 'unknown/unknown')
                    lines.append(f'{pkg}  # GitHub: {repo} -- commit unknown')
        else:
            lines += [
                '# R repository detected.',
                '# If using renv: run renv::restore() to install dependencies.',
                '# If not using renv: add your R package dependencies manually.',
            ]
    elif '.do' in all_suffixes or '.ado' in all_suffixes:
        lines += [
            '# Stata repository detected.',
            '# List required Stata packages (ssc install) manually.',
        ]
    elif '.m' in all_suffixes:
        # Scan .m files for inline toolbox requirements
        toolbox_pattern = re.compile(r'[(%]?requires?\s+([\w\s]+(?:Toolbox|EEGLAB))', re.IGNORECASE)
        eeglab_fns = {'pop_epoch', 'pop_autorej', 'pop_resample', 'pop_eegfiltnew',
                      'eeglab', 'pop_loadset', 'pop_saveset', 'runica'}
        found_toolboxes = set()
        found_eeglab = False
        for mf in all_files:
            if mf.suffix.lower() == '.m':
                try:
                    msrc = mf.read_text(encoding='utf-8', errors='ignore')
                    for m in toolbox_pattern.finditer(msrc):
                        tb = m.group(1).strip()
                    # Normalise abbreviated MathWorks names to full current names
                    if tb.lower() in {'statistics toolbox', 'statistics and machine learning toolbox'}:
                        tb = 'Statistics and Machine Learning Toolbox'
                    found_toolboxes.add(tb)
                    if any(fn in msrc for fn in eeglab_fns):
                        found_eeglab = True
                except Exception:
                    pass
        if found_eeglab:
            found_toolboxes.add('EEGLAB (third-party — download from sccn.ucsd.edu/eeglab)')
        if found_toolboxes:
            lines += ['# MATLAB repository detected.',
                      '# Required toolboxes detected from code comments:']
            for tb in sorted(found_toolboxes):
                lines.append(f'# - {tb}')
            lines += ['# Verify these are licensed and installed before running.', '']
        else:
            lines += [
                '# MATLAB repository detected.',
                '# List required MATLAB toolboxes manually.',
        ]
    else:
        lines += [
            '# No external imports detected.',
            '# Add your dependencies manually.',
        ]

    lines += [
        '',
        '# ============================================================',
        '# Local modules found in this repository (excluded above):',
    ]
    for m in sorted(local_modules):
        lines.append(f'# {m}')
    lines.append('# ============================================================')

    out = output_dir / 'requirements_DRAFT.txt'
    out.write_text('\n'.join(lines), encoding='utf-8-sig')
    print(f"  → requirements_DRAFT.txt "
          f"({len(external)} packages detected)")


# ── QUICKSTART_DRAFT.md ──────────────────────────────────────────────────────


def _renumber_steps(steps):
    """Resequence numbered steps (lines starting with a digit and .) after deletions."""
    result = []
    n = 1
    for s in steps:
        import re as _re
        if _re.match(r'^\d+\.', s):
            s = _re.sub(r'^\d+\.', f'{n}.', s, count=1)
            n += 1
        elif s.startswith('N.'):
            s = s.replace('N.', f'{n}.', 1)
            n += 1
        result.append(s)
    return result


def _quickstart_step2(all_files, code_files):
    """Return language-appropriate step 2 for QUICKSTART."""
    suffixes = {f.suffix.lower() for f in code_files}
    if any(f.name == 'Snakefile' for f in all_files):
        suffixes.add('.smk')
    names = {f.name.lower() for f in all_files}
    # conda repo takes priority — single env file replaces all other dep steps
    if 'environment.yml' in names or 'environment.yaml' in names:
        env_file = 'environment.yml' if 'environment.yml' in names else 'environment.yaml'
        env_name = 'myenv'
        env_path = next((f for f in all_files if f.name.lower() == env_file), None)
        if env_path:
            import re as _re
            m = _re.search(r'^name:\s*(\S+)', env_path.read_text(encoding='utf-8', errors='ignore'), _re.MULTILINE)
            if m:
                env_name = m.group(1)
        return [f'2. Create and activate environment: `conda env create -f {env_file} && conda activate {env_name}`']
    if '.r' in suffixes or '.rmd' in suffixes:
        return ['2. Add version numbers to packages in `requirements_DRAFT.txt`, '
                'then run `renv::snapshot()` to create `renv.lock`']
    if '.smk' in suffixes or any(f.name == 'Snakefile' for f in all_files):
        return ['2. Run the Snakemake workflow: `snakemake --cores all`',
                '   (add --use-conda if per-rule conda: directives are present)']
    if '.jl' in suffixes:
        names = {f.name.lower() for f in all_files}
        if 'project.toml' in names:
            return ['2. Dependencies managed by `Project.toml` — run '
                    '`julia --project=. -e "using Pkg; Pkg.instantiate()"`']
        else:
            # No Project.toml — manually install detected packages
            jl_pkgs = sorted({
                pkg for f in all_files if f.suffix.lower() == '.jl'
                for line in f.read_text(encoding='utf-8', errors='ignore').splitlines()
                for m in [__import__('re').match(r'^using\s+([\w,\s]+)', line.strip())]
                if m
                for pkg in __import__('re').split(r'[,\s]+', m.group(1))
                if pkg.strip() and pkg.strip() not in {
                    'Random','Statistics','LinearAlgebra','Dates','Printf',
                    'Base','Core','Main','Pkg','Test','Logging','REPL',
                    'InteractiveUtils','Distributed','Serialization',
                    'Markdown','Unicode','DelimitedFiles','SparseArrays'}
            })
            if jl_pkgs:
                pkg_list = ', '.join(f'"{p}"' for p in jl_pkgs)
                return [f'2. Install required packages: `julia -e \'using Pkg; Pkg.add([{pkg_list}])\'`']
            return ['2. Install required Julia packages manually using `julia -e "using Pkg; Pkg.add(\"PackageName\")"`']
    # check for pyproject.toml package
    names = {f.name.lower() for f in all_files}
    if 'pyproject.toml' in names:
        return ['2. Install as editable package: `pip install -e .`']
    # Python — check if already pinned
    has_pinned = any(
        f.name.lower() in DEPENDENCY_FILES and
        any('==' in l for l in f.read_text(encoding='utf-8', errors='ignore').splitlines()
            if not l.strip().startswith('#'))
        for f in all_files if f.name.lower() in DEPENDENCY_FILES
    )
    has_requirements = any(f.name.lower() == 'requirements.txt' for f in all_files)
    if has_pinned:
        # Check if any requirements*.txt has git+ URLs or loose constraints
        import re as _reqs
        req_files_qs = [f for f in all_files if _reqs.match(r'requirements.*\.txt$', f.name.lower())]
        has_git_urls = any(
            any(l.strip().startswith('git+') for l in f.read_text(encoding='utf-8', errors='ignore').splitlines())
            for f in req_files_qs
        )
        extra_reqs = [f.name for f in req_files_qs if f.name.lower() != 'requirements.txt']
        if has_git_urls:
            return ['2. Install dependencies (WARNING: git+ URLs present — pin to commit SHA before deposit):',
                    'pip install -r requirements.txt',
                    *[f'pip install -r {n}' for n in extra_reqs]]
        elif extra_reqs:
            return ['2. Install all dependencies:',
                    'pip install -r requirements.txt',
                    *[f'pip install -r {n}  # additional dependencies' for n in extra_reqs]]
        return ['2. Your `requirements.txt` already has pinned versions — no changes needed']
    if has_requirements:
        return ['2. Pin the version numbers in your existing `requirements.txt` (e.g. pandas==2.1.3)']
    return ['2. Add version numbers to `requirements_DRAFT.txt` and rename to `requirements.txt`']

def _install_instructions(code_files, all_files=None):
    """Return language-appropriate install instructions."""
    suffixes = {f.suffix.lower() for f in code_files}
    lines = []
    # conda repo — step 2 already covers install via _quickstart_step2; suppress step 3
    if all_files:
        names = {f.name.lower() for f in all_files}
        if 'environment.yml' in names or 'environment.yaml' in names:
            return []
    # Julia: step 2 already covers install via _quickstart_step2; suppress step 3
    if '.jl' in suffixes:
        return []  # handled in step 2
    if '.r' in suffixes or '.rmd' in suffixes:
        lines.append('3. Install R dependencies: `Rscript -e "renv::restore()"`')
    if '.do' in suffixes or '.ado' in suffixes:
        lines.append('3. Open Stata and run the master do-file listed above')
    if '.m' in suffixes:
        lines.append('3. Open MATLAB and run the master script listed above')
    if '.py' in suffixes or not lines:
        lines.append('3. Install dependencies: `pip install -r requirements.txt`')
    return lines

def _generate_quickstart_draft(repo_dir, all_files,
                                 findings, output_dir):
    """Generate QUICKSTART_DRAFT.md with inferred execution order."""

    now = datetime.now().strftime('%Y-%m-%d %H:%M')

    archive_dirs = {"old", "archive", "deprecated", "unused", "backup", "old_versions"}
    code_files = [
        f for f in all_files
        if (f.suffix.lower() in CODE_EXTENSIONS or f.name == 'Snakefile')
        and f.name not in {"__init__.py", "__main__.py"}
        and not any(p.name.lower() in archive_dirs for p in f.parents)
    ]

    # try to find numbered scripts
    numbered = []
    for f in code_files:
        m = re.match(r'^(0*)([0-9]+)[_\-](.+)', f.name)
        if m:
            numbered.append((int(m.group(2)), f))
    numbered.sort(key=lambda x: x[0])

    lines = [
        '# ValiChord Repository Readiness Check — Quick Start',
        '',
        '> ⚠️ **IMPORTANT — THIS EXECUTION ORDER IS INFERRED**',
        '> **AND HAS NOT BEEN VALIDATED.**',
        '> ',
        '> The script order below was generated by automated',
        '> analysis and may be incorrect. Do not rely on it',
        '> without manual verification against your own',
        '> knowledge of the pipeline.',
        '> ',
        '> **Confidence level: LOW**',
        '',
        '---',
        '',
    ]

    if numbered:
        lines += [
            '## Inferred Execution Order',
            '(from numbered script filenames)',
            '',
        ]
        for num, f in numbered:
            rel = f.relative_to(repo_dir)
            lines.append(f'{num}. `{rel}`')
        lines.append('')
    else:
        lines += [
            '## Script Files Found',
            '',
            'No numbered scripts detected. '
            'The following scripts were found — ',
            'you must specify the correct execution order:',
            '',
        ]
        for f in sorted(code_files, key=lambda x: x.name):
            rel = f.relative_to(repo_dir)
            lines.append(f'- `{rel}`')
        # also list notebooks
        notebook_files = [f for f in all_files if f.suffix.lower() in NOTEBOOK_EXTENSIONS]
        for f in sorted(notebook_files, key=lambda x: x.name):
            rel = f.relative_to(repo_dir)
            lines.append(f'- `{rel}` (open in Jupyter and run all cells top to bottom)')
        lines.append('')

    lines += [
        '---',
        '',
        '## Before Running',
        '',
        *_renumber_steps([
            '1. Complete `README_DRAFT.md` and rename to `README.md`',
            *(_quickstart_step2(all_files, code_files)),
            *_install_instructions(code_files, all_files),
            'N. Test on a **clean machine** — not just a new folder '
            'on your development machine',
        ]),
        '',
        '---',
        '',
        f'*Generated by ValiChord Repository Readiness Check v15 — {now}*',
    ]

    out = output_dir / 'QUICKSTART_DRAFT.md'
    out.write_text('\n'.join(lines), encoding='utf-8-sig')
    print(f"  → QUICKSTART_DRAFT.md")


# ── LICENCE_DRAFT.txt ────────────────────────────────────────────────────────

def _generate_licence_draft(output_dir, all_files=None):
    """Generate LICENCE_DRAFT.txt."""

    now = datetime.now().strftime('%Y-%m-%d %H:%M')
    year = datetime.now().year

    content = f"""LICENCE_DRAFT.txt — generated by ValiChord Repository Readiness Check v15
Generated: {now}

YOU MUST COMPLETE THIS FILE before sharing your repository.

Choose one of the following options and replace this entire
file with your chosen licence text.

============================================================
RECOMMENDED FOR CODE: MIT Licence
============================================================

MIT License

Copyright (c) {year} [YOUR NAME]

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or
sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.

============================================================
RECOMMENDED FOR DATA: Creative Commons CC-BY 4.0
============================================================

If your repository includes data, consider licensing it under
Creative Commons Attribution 4.0 International (CC-BY 4.0).

See: https://creativecommons.org/licenses/by/4.0/

============================================================
IMPORTANT QUESTIONS TO ANSWER BEFORE CHOOSING:
============================================================

1. Does your data include human subjects data?
   If yes: do you have authorisation to share it?

2. Does your code use any GPL-licensed libraries?
   If yes: your code may need to be GPL-licensed too.

3. Does your institution have a default IP policy?
   If yes: check whether you need institutional approval.

4. Does your funder require a specific open licence?
   If yes: use that licence.

============================================================
Rename this file to LICENCE (no extension) or LICENCE.md
after completing it.
============================================================
"""

    out = output_dir / 'LICENCE_DRAFT.txt'
    out.write_text(content, encoding='utf-8-sig')
    print(f"  → LICENCE_DRAFT.txt")


# ── README placeholder ───────────────────────────────────────────────────────


def generate_proposed_corrections(repo_dir, all_files, findings, output_dir):
    """Generate corrected file copies in /proposed_corrections/."""

    corrections_dir = output_dir / 'proposed_corrections'
    corrections_dir.mkdir(exist_ok=True)

    # get all [C] absolute path findings
    path_findings = [f for f in findings if f['mode'] == 'C']

    if not path_findings:
        return

    # write a README for the corrections folder
    readme_lines = [
        '# proposed_corrections/',
        '',
        '> ⚠️ **THESE FILES CONTAIN A DELIBERATE RUNTIME ERROR.**',
        '> They will not execute until you remove the error block',
        '> at the top of each file.',
        '>',
        '> This is intentional. You must review each correction',
        '> before using it. The tool cannot guarantee that the',
        '> relative path replacements are correct for your setup.',
        '',
        '## How to use these files',
        '',
        '1. Open each file and read the correction at the top',
        '2. Verify the relative path is correct for your directory structure',
        '3. Remove the `raise RuntimeError` block at the top',
        '4. Replace the corresponding file in your repository',
        '5. Test that your code still runs correctly',
        '',
        '## Files corrected',
        '',
    ]

    corrected_files = []

    for path_finding in path_findings:
        # extract filename from evidence
        evidence = path_finding.get('evidence', [])
        if not evidence:
            continue

        fname = path_finding['detail']
        # find the actual file
        target_files = [
            f for f in all_files
            if path_finding['evidence'][0].startswith(
                f'Evidence: {f.name}'
            )
        ]

        if not target_files:
            continue

        src_file = target_files[0]

        try:
            content = src_file.read_text(encoding='utf-8', errors='ignore')
        except Exception:
            continue

        # find and replace absolute paths
        abs_pattern = re.compile(
            r'(/Users/[a-zA-Z][a-zA-Z0-9_\-]{1,}/[^\s\'")\]]*)'
            r'|(/home/[a-zA-Z][a-zA-Z0-9_\-]{1,}/[^\s\'")\]]*)'
            r'|(/root/[a-zA-Z][^\s\'")\]]*)'
            r'|([A-Z]:\\\\[A-Za-z][^\s\'")\]]*)'
            r'|([A-Z]:/[A-Za-z][^\s\'")\]]*)'
        )

        matches = abs_pattern.findall(content)
        flat_matches = [m for group in matches for m in group if m]

        if not flat_matches:
            continue

        corrected = content
        replacements = []

        for match in flat_matches:
            # generate a relative path suggestion
            # extract just the filename/last component
            parts = match.replace('\\', '/').rstrip('/').split('/')
            suggested = './data/' + parts[-1] if parts else './data/file'
            corrected = corrected.replace(match, suggested, 1)
            replacements.append((match, suggested))

        # build the warning block
        warning_lines = [
            '# ============================================================',
            '# VALICHORD PROPOSED CORRECTION — DO NOT RUN WITHOUT REVIEWING',
            '# ============================================================',
            '# This file was generated by ValiChord Repository Readiness Check.',
            '# The following absolute paths were detected and replaced',
            '# with suggested relative paths:',
            '#',
        ]
        for orig, sugg in replacements:
            warning_lines.append(f'#   ORIGINAL:  {orig}')
            warning_lines.append(f'#   SUGGESTED: {sugg}')
            warning_lines.append('#')
        warning_lines += [
            '# VERIFY each replacement before using this file.',
            '# The suggested paths may not match your directory structure.',
            '# ============================================================',
            '',
            'raise RuntimeError(',
            '    "VALICHORD PROPOSED CORRECTION: Remove this error block "',
            '    "after verifying the path corrections above."',
            ')',
            '',
            '# ============================================================',
            '',
        ]

        warning_block = '\n'.join(warning_lines) + '\n'
        final_content = warning_block + corrected

        out_file = corrections_dir / src_file.name
        out_file.write_text(final_content, encoding='utf-8-sig')
        corrected_files.append(src_file.name)

    # write the corrections README — consolidate duplicate filenames
    from collections import Counter
    file_counts = Counter(corrected_files)
    for fname, count in sorted(file_counts.items()):
        if count > 1:
            readme_lines.append(f'- `{fname}` ({count} corrections)')
        else:
            readme_lines.append(f'- `{fname}`')

    readme_lines += [
        '',
        '---',
        '',
        f'*Generated by ValiChord Repository Readiness Check v15*',
    ]

    readme_out = corrections_dir / 'README.md'
    readme_out.write_text('\n'.join(readme_lines), encoding='utf-8-sig')

    print(f"  → proposed_corrections/ ({len(corrected_files)} files)")