"""
ValiChord Auto-Generate
Cleaning Report Generator
Produces CLEANING_REPORT.md and ASSESSMENT.md
"""

from pathlib import Path
from datetime import datetime


def generate_cleaning_report(repo_name, repo_dir, all_files,
                              findings, output_dir):
    """Generate CLEANING_REPORT.md and ASSESSMENT.md."""

    _write_cleaning_report(repo_name, repo_dir, all_files,
                           findings, output_dir)
    _write_assessment(repo_name, findings, output_dir)


def _severity_emoji(severity):
    return {
        'CRITICAL': '🔴',
        'SIGNIFICANT': '🟡',
        'LOW CONFIDENCE': '🔵',
    }.get(severity, '⚪')


def _write_cleaning_report(repo_name, repo_dir, all_files,
                            findings, output_dir):

    critical   = [f for f in findings if f['severity'] == 'CRITICAL']
    significant = [f for f in findings if f['severity'] == 'SIGNIFICANT']
    low        = [f for f in findings if f['severity'] == 'LOW CONFIDENCE']

    now = datetime.now().strftime('%Y-%m-%d %H:%M')

    lines = []

    # ── header ───────────────────────────────────────────────────────
    lines += [
        ''# ValiChord Repository Readiness Check — Cleaning Report',',
        '',
        '> ⚠️ **ANTI-AUTHORITY NOTICE**',
        '> ',
        '> This report was generated by automated analysis. '
        'None of the proposed',
        '> improvements have been validated by running the code. '
        'The researcher',
        '> is responsible for all decisions about the final state '
        'of this repository.',
        '> All generated files have `_DRAFT` in their names and '
        'must be verified',
        '> before use.',
        '',
        f'**Repository:** {repo_name}',
        f'**Processed:** {now}',
        f'**ValiChord Spec:** v15',
        f'**Files analysed:** {len(all_files)}',
        '',
    ]

    # ── researcher warning (Form A) ──────────────────────────────────
    lines += [
        '---',
        '',
        '## ⚠️ Important — Read Before Proceeding',
        '',
        'This tool has organised your repository and filled in missing '
        'documentation, preparing it for independent validation.',
        '',
        'Because the tool only reads your files and does not run your '
        'code, it cannot assess whether your analysis is correct, '
        'statistically sound, or free from error. '
        '**It only ensures your files are organised and documented.**',
        '',
        '**If anything this tool has generated contradicts your '
        'knowledge of your own research, the tool is wrong.** '
        'Any conflict must be resolved in your favour.',
        '',
        '**If your cleaned repository runs end-to-end but produces '
        'results that differ from your published paper, this is not '
        ''a ValiChord Repository Readiness Check error.** First check whether you adopted any proposed corrections — a correction may have introduced a change. If no corrections were adopted and results still differ, this is a scientific discrepancy only ' '
        'you can resolve.',
        '',
        '**This report does not constitute certification that this '
        'repository is reproducible.** It identifies packaging '
        'problems and generates draft improvements. Running your '
        'pipeline on a genuinely clean machine is the only reliable '
        'test.',
        '',
    ]

    # ── summary table ────────────────────────────────────────────────
    lines += [
        '---',
        '',
        '## Summary',
        '',
        '| Severity | Count |',
        '|---|---|',
        f'| 🔴 CRITICAL | {len(critical)} |',
        f'| 🟡 SIGNIFICANT | {len(significant)} |',
        f'| 🔵 LOW CONFIDENCE | {len(low)} |',
        f'| **Total findings** | **{len(findings)}** |',
        '',
    ]

    # minimal findings note
    if len(critical) == 0 and len(significant) == 0:
        lines += [
            '> ✅ **No CRITICAL or SIGNIFICANT findings detected.**',
            '> This means common packaging problems were not found — '
            'it does not mean',
            '> the repository is verified as reproducible. Running '
            'the complete pipeline',
            '> on a clean machine remains the only reliable test.',
            '',
        ]

    # ── findings by severity ─────────────────────────────────────────
    for severity, group in [
        ('CRITICAL', critical),
        ('SIGNIFICANT', significant),
        ('LOW CONFIDENCE', low),
    ]:
        if not group:
            continue

        emoji = _severity_emoji(severity)
        lines += [
            '---',
            '',
            f'## {emoji} {severity} Findings',
            '',
        ]

        for f in group:
            lines += [
                f'### [{f["mode"]}] {f["title"]}',
                '',
                f['detail'],
                '',
            ]
            if f.get('evidence'):
                for e in f['evidence']:
                    lines.append(f'- `{e}`')
                lines.append('')

    # ── generated files list ─────────────────────────────────────────
    lines += [
        '---',
        '',
        '## Generated Files',
        '',
        'The following `_DRAFT` files have been generated. '
        'Each must be verified and renamed (remove `_DRAFT`) '
        'before use.',
        '',
        '| File | Purpose |',
        '|---|---|',
        '| `README_DRAFT.md` | Repository documentation template |',
        '| `requirements_DRAFT.txt` | Dependency skeleton '
        '(versions UNKNOWN) |',
        '| `QUICKSTART_DRAFT.md` | Inferred execution order |',
        '| `LICENCE_DRAFT.txt` | Licence template |',
        '| `INVENTORY_DRAFT.md` | File inventory |',
        '| `ASSESSMENT.md` | Detailed assessment questions |',
        '',
        '> All files in `/proposed_corrections/` contain a runtime '
        'error by design.',
        '> They will not execute until you actively remove that error.',
        '',
        '---',
        '',
        f'*ValiChord Repository Readiness Check — Assessment — '
        f'Specification v15 — {now}*',
        '*© 2026 Ceri John. All Rights Reserved.*',
    ]

    out = output_dir / 'CLEANING_REPORT.md'
    out.write_text('\n'.join(lines), encoding='utf-8-sig')
    print(f"  → CLEANING_REPORT.md")


def _write_assessment(repo_name, findings, output_dir):
    """Generate ASSESSMENT.md with questions for the researcher."""

    now = datetime.now().strftime('%Y-%m-%d %H:%M')

    lines = [
        '# ValiChord Auto-Generate — Assessment',
        '',
        f'**Repository:** {repo_name}',
        f'**Generated:** {now}',
        '',
        'This file contains questions and action items for the '
        'researcher to complete. These cannot be answered by '
        'automated analysis — only you know the answers.',
        '',
        '---',
        '',
        '## Action Items',
        '',
    ]

    # generate action items from findings
    action_map = {
        'A':  'Complete all placeholder sections in README_DRAFT.md, '
              'especially the study overview and definition of '
              'successful reproduction.',
        'B':  'Add exact version numbers to all packages marked '
              'UNKNOWN in requirements_DRAFT.txt. Run '
              '`pip freeze` in your original environment to get them.',
        'C':  'Review corrected path files in /proposed_corrections/ '
              'and verify each relative path is correct before '
              'applying.',
        'D':  'Verify the execution order in QUICKSTART_DRAFT.md '
              'matches your actual pipeline.',
        'N':  'Choose a licence for your code and data and complete '
              'LICENCE_DRAFT.txt.',
        'Z':  'Add the commit hash or version tag for this exact '
              'deposit to your README.',
        'W':  'Run `git lfs pull` before creating your deposit ZIP '
              'to include actual data files.',
        'BJ': 'Provide decryption keys separately to validators, '
              'or replace encrypted files with the actual data if '
              'sharing is permitted.',
        'BK': 'Replace clock-based filenames with fixed names, '
              'and replace clock-based seeds with fixed integers.',
        'BL': 'Pin your version number explicitly. Replace '
              'setuptools_scm / versioneer with '
              '`__version__ = "1.0.0"` in your package.',
    }

    modes_found = {f['mode'] for f in findings}
    added = False

    for mode, action in action_map.items():
        if mode in modes_found:
            lines += [f'- **[{mode}]** {action}', '']
            added = True

    if not added:
        lines += [
            '✅ No specific action items generated from current '
            'findings.',
            '',
        ]

    # standard questions always asked
    lines += [
        '---',
        '',
        '## Standard Verification Questions',
        '',
        'Please answer these regardless of the findings above:',
        '',
        '1. **Definition of successful reproduction:** What exactly '
        'should a validator see when they have successfully reproduced '
        'your results? Include numerical values and tolerance bands '
        'where relevant.',
        '',
        '2. **Data provenance:** Where did each data file come from? '
        'If any data is anonymised or synthetic, document the '
        'transformation.',
        '',
        '3. **Platform sensitivity:** Did you run this on a specific '
        'OS, GPU, or hardware configuration? Do results differ '
        'across platforms?',
        '',
        '4. **Stochasticity:** Are any results expected to vary '
        'between runs? If so, by how much?',
        '',
        '5. **Figure mapping:** Which script produces which figure '
        'in your paper? Please complete this mapping:',
        '',
        '   | Paper Figure | Generated File | Script |',
        '   |---|---|---|',
        '   | Figure 1 | | |',
        '   | Figure 2 | | |',
        '   | Figure 3 | | |',
        '',
        '6. **Manual steps:** Are there any steps in your analysis '
        'that cannot be automated — e.g., manual data entry, '
        'GUI-based steps, or proprietary software exports?',
        '',
        '---',
        '',
        f'*Generated by ValiChord Repository Readiness Check — '
        f'Specification v15 — {now}*',
    ]

    out = output_dir / 'ASSESSMENT.md'
    out.write_text('\n'.join(lines), encoding='utf-8-sig')
    print(f"  → ASSESSMENT.md")